### ISSUE TITLE
Data bind to a date field

### ISSUE THREAD

**Issue by poppie** [dsuryd/dotNetify#10]
What is the best way to bind to a date?

First line works perfectly without data binding, the second is receiving:

The specified value "1975-01-13T00:00:00" does not conform to the required format, "yyyy-MM-dd".

```
                                @Html.TextBoxFor(model => model.ActiveOccupant.DateOfBirth, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control" })
                                @Html.TextBoxFor(model => model.ActiveOccupant.DateOfBirth, "{0:yyyy-MM-dd}", new { type = "date", @class = "form-control", data_bind = "value: ActiveOccupant.DateOfBirth" })
```

**Comment by dsuryd** [comment]
There is no built-in knockout binding for dates, but people has solved it by creating their own custom binding.  See this one for example:  https://github.com/adrotec/knockout-date-bindings.

**Comment by poppie** [comment]
Thanks, using the knockout-date-bindings and a minor change to dotnetify.js

          // Added RR: to format dates for dotnetify
          if (iNewValue.toLocaleDateString != undefined) {
              var month = iNewValue.getMonth() + 1;
              update[iVMPath] = iNewValue.getFullYear() + '/' + month + '/' + iNewValue.getDate();
          } else {
              update[iVMPath] = iNewValue instanceof Object ? $.extend({}, iNewValue) : iNewValue;
          }

it works like a top.
