### ISSUE TITLE
C# Client Support

### ISSUE THREAD

**Issue by rsalayo** [dsuryd/dotNetify#102]
Can I still use SignalR client to connect to /dotnetify as a hub?
Say I want to make a Server/Client type solution where I have thousands of SignalR Clients (C#) connecting to DotNetify (Server).

I would like to use the C# Client to register/update connectionId and use DotNetify clients (browser) to control/send command to C# Client(s).

**Comment by rsalayo** [comment]
Ahh yes, using
`connection.InvokeAsync<string>("Update_VM", vmId, vmData);`

**Comment by rsalayo** [comment]
How do I get the connectionId of client from the VM?
`public Action<string> Add => args => { ... };`
or
`this.AddProperty<Client>("Add").Subscribe(args => { ... });`

**Comment by dsuryd** [comment]
View models by default are isolated from the lower level infrastructure, but you can circumvent that by writing a custom [**View Model Filter**](http://dotnetify.net/react/Filter).

VM filters have access to both SignalR hub context and their VM instances, so you can use one to fetch the connection ID and inject it into the instance.  For details, check out the [access token filter example](https://github.com/dsuryd/dotNetify/blob/master/ASP.NET%20Core%20Demo/WebApplication.React/ExamplePipelines/SetAccessTokenFilter.cs).

**Comment by qcjxberin** [comment]
How long does it take for this feature to be completed?

**Comment by tw-bert** [comment]
Amazing stuff Dicky! Great that you chose to implement this.
