### ISSUE TITLE
Intermittent DotNetify client sending.

### ISSUE THREAD

**Issue by bhgjmorton** [dsuryd/dotNetify#103]
Hi! 

In a project Im working on. I only want the dotnetify client connection to receive a "true" boolean from the server back-end on an intermittent basis when certain information has changed. I am doing this by setting a timer in a react C# controller that performs a check and then sends the value if the condition is met. 

This works on the initial pass but does not on any subsequent passes. Is this functionality possible with DotNetify?

**Comment by dsuryd** [comment]
Did you call PushUpdate() ? It's required if the server initiates data push.

**Comment by bhgjmorton** [comment]
I believe I'm doing this correctly but, I of course could be wrong. I'll post the code.
Here is the DotNetify change class.
`public class InfoChange : BaseVM
        {
            public bool mInfoChange => true;

            public void sendChange()
            {
                Changed(nameof(mInfoChange));
                PushUpdates();
            }
        }`
This is used in a React Controller timer to push updates when conditions are met. Do you see something at issue in this?
`mTimer = new Timer(state =>
            {
                if (ConnectionToService.Instance.IsConnected)
                {
                    int InformationVersion = mConnection.Service.InvokeAsync<int>("CheckInformationVersion").Result
                    if (InformationVersion > mInfoVersion)
                    {
                        //Only send the True boolean when the version has changed from the other application
                        InfoChange.sendChange();
                    }
                }
            }, null, 1000, 1000);`

**Comment by dsuryd** [comment]
The code looks okay, but let's turn on the debugging.  In the React code, call `dotnetify.debug = true'.  Witht this on, you should be able to see in the browser's console log incoming server data.  Check whether the server does send the 'true' value when it needs to.  If it does, then the problem is in the React view not refreshing, probably because the value doesn't change.

**Comment by bhgjmorton** [comment]
I have turned that on and am able to see the initial message on page opening being received by the Front End. However, on any subsequent call to PushUpdates() the FrontEnd does not receive any message. The code does seem to be running correctly on the BackEnd. 

Thanks a ton for your help with this!

**Comment by dsuryd** [comment]
It seems the timer is calling a static instance of InfoChange, which is probably not the same instance as the one being used to communicate with the client.  Can you move that timer to inside the view model class and call locally?

**Comment by bhgjmorton** [comment]
We got this figured out today by doing exactly that. Moving the timer back inside the view model and pushing the changed data from there rather than a boolean that told our front end client when things were changed. 

Thanks a lot for the help!
