### ISSUE TITLE
Impressive!

### ISSUE THREAD

**Issue by ensemblebd** [dsuryd/dotNetify#106]
Just wanted to say thanks

**Comment by dsuryd** [comment]
You're welcome 👍

**Comment by AlwaysHC** [comment]
This project is what it missed, how can I help you?

**Comment by dsuryd** [comment]
Anything that's aligned to your skill and interest, really.   There are enhancement requests for Blazor and Vue integration, if that's your cup of tea.   This project also can do with more promotion, maybe write  some tutorial blogs, or create an impressive sample app and write your experience in well-known developer sites.

**Comment by ensemblebd** [comment]
I will definitely do so.

I work for a small web development firm, and over the years I've become somewhat of a "lone high-chair" developer. Wasn't part of the plan, but it is what it is. I've found that to produce great works, you have to mentally assimilate the project in it's entirety. Which is apparently a rare skill. 

We have two major projects serving clients nationally, and I will be refactoring the codebases (severely outdated tech) to utilize **this** boilerplate. This boilerplate is **SO good**, that it can be done with great ease, and so I hope my words of "thank you" stress just how wonderful of a job you've done on this!!

It will take 3 to 5 months before my work will be done. But once complete, I'll make certain we give credit to you and publish a tech review where applicable. 

Will post back later this year when that comes to pass. :)

**Comment by dsuryd** [comment]
Thank you, you just made my day 🙂
