### ISSUE TITLE
Any React SSR examples available?

### ISSUE THREAD

**Issue by mrayva** [dsuryd/dotNetify#107]
See some JS code, but no CS. Not sure if SSR is possible at all with dotNetify

**Comment by dsuryd** [comment]
There's link to SSR article at the end of the Routing doc.

**Comment by dsuryd** [comment]
I just checked the example; unfortunately the SSR portion is no longer working.

**Comment by mrayva** [comment]
I guess, https://github.com/dsuryd/dotnetify-react-demo-vs2017/tree/master/Routing is a decent SSR example...?

**Comment by dsuryd** [comment]
That's the one that I said wasn't working anymore.

**Comment by mrayva** [comment]
Not sure what part is not working - superficially - looks ok... 
Outside VS2017, running "dotnet run", and navigating to http://localhost:61201/,
I see

> fail: Microsoft.AspNetCore.NodeServices[0]
>       Server-side rendering requires initial state in 'window.ssr.Page1'.
> 

dumped into console...

**Comment by dsuryd** [comment]
The app is still functional, but it's all client-side rendering.   The server should have rendered the complete HTML on first request (see page source to verify), and you won't see any flashing.  But as it stands now, it no longer does that - something gets broken in the routing ssr code in the dotnetify script.

**Comment by dsuryd** [comment]
The SSR example is now fixed.

**Comment by mrayva** [comment]
Thanks for all the hard work!
