### ISSUE TITLE
Publishing Guidance

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#109]
Hi Dicky - Thanks so much for being so responsive to us on this forum!! I need some guidance from you on publishing my combined c#/react application. I started with your create-react-app hello world example (http://dotnetify.net/react/create-react-app) but moved all of my c# code into a folder called "middle-tier". Now, I am ready to publish everything so that it runs on my target that only has runtime .Net core. Any guidance that you can give me would be helpful!!

Thanks,
Dave

**Comment by dsuryd** [comment]
My pleasure!

Take a look this:
- https://github.com/dsuryd/dotnetify-react-demo-vs2017/issues/6
- https://github.com/dsuryd/dotnetify-react-demo-vs2017/blob/master/LiveChart/IISPublishingSteps.md

**Comment by mojo-man** [comment]
Thanks - but I'm running in debian-ish linux, dotnet core, kestrel, etc.

**Comment by mojo-man** [comment]
Thanks - I will do that.
