### ISSUE TITLE
View and VM are loaded multiple times when using redirect

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#11]
I first thought that I missed something, but the problem is also noticable on your webstore example.
When you click the link inside the carousel to books category, it is loaded two times. You can easily notice it by monitoring the network traffic with chrome.

In my case I have a MainPage that loads multiple subbpages. The Routes to these subpages are registered in the MainPageVM. The subpages then contains buttons to navigate to each other which are created using Redirect. But with each subpage that uses Redirect, the page will load as many times as Redirect to this page has been called.

**Comment by dsuryd** [comment]
Thanks, I'll look into it.

**Comment by dsuryd** [comment]
Made an update to dotnetify.router.js to fix this issue.  Please test and let me know. Thanks.

**Comment by DG4ever** [comment]
Great now it's working as expected.
