### ISSUE TITLE
Initializing data in the ViewModel constructor asynchronously

### ISSUE THREAD

**Issue by debuggingmyhead** [dsuryd/dotNetify#110]
I was wondering if you had any thoughts on the following scenario: In the constructor of the ViewModel, a data access service is injected. In order to get initial data for some properties, an async method on the service must be awaited (within the constructor). How should that be handled?

After doing a bit of googling, it seems a good solution to this is the factory pattern of first creating the VM instance and then awaiting some function like "InitializeAsync" on the instance. I was considering modifying how dotNetify creates VM instances but after looking at the code it looks like I would have to potentially alter many different aspects to be async.

I'm still a bit inexperienced with async and MVVM patterns, though, so perhaps I'm going about it the wrong way or missing something obvious. Any insight is greatly appreciated.

**Comment by dsuryd** [comment]
Great question!  I would run a Task from the view model's constructor to execute the asynchronous call, assign the result to a property, and finally use `PushUpdates()` to update the client.

```csharp
public class MyVM : BaseVM
{
  public MyVM()
  {
      var result = AddProperty<string>("Result");

      Task.Run(async () =>
      {
          result.Value = await DoWorkAsync();
          PushUpdates();
      });
  }

  private Task<string> DoWorkAsync()
  {
      return Task.Run(() =>
      {
          Thread.Sleep(2000);
          return "Async work complete";
      });
  }
}
```

**Comment by debuggingmyhead** [comment]
Thanks for the response, that looks like a great solution. Do you know if running the task from the constructor like that would ever cause blocking on the UI thread?

**Comment by dsuryd** [comment]
Unless you explicitly read its Result property, Task is non-blocking.

**Comment by debuggingmyhead** [comment]
Excellent. Appreciate the help!

**Comment by illumen** [comment]
@dsuryd How would you deal with multiple async calls? 
E.g.
`Task.Run(async () =>
      {
          result1.Value = await DoWorkAsync1();
          PushUpdates();
      });

Task.Run(async () =>
      {
          result2.Value = await DoWorkAsync2();
          PushUpdates();
      });

Task.Run(async () =>
      {
          result3.Value = await DoWorkAsync3();
          PushUpdates();
      });`

Sometimes DoWorkAsync2() will finish just after DoWorkAsync3() and thus miss pushing the update...

**Comment by dsuryd** [comment]
I wasn't able to reproduce the push failure with your example above and playing with different Thread.Sleep duration, but in general if you don't need to immediately push per incoming result, I suggest you just wait until all results are received before calling PushUpdates.   Either you use Task Parallel library,  or use ReactiveX like this:
```csharp
using System;
using System.Reactive;
using System.Reactive.Linq;
...
var result1 = AddProperty<string>("Result1");
var result2 = AddProperty<string>("Result2");
var result3 = AddProperty<string>("Result3");

Observable.Zip(
   Observable.FromAsync(() => DoWork1Async()),
   Observable.FromAsync(() => DoWork2Async()),
   Observable.FromAsync(() => DoWork3Async()),
   (v1, v2, v3) =>
   {
       result1.Value = v1;
       result2.Value = v2;
       result3.Value = v3;
       return true;
   })
   .Subscribe(x => PushUpdates());
```

**Comment by desarrollo03TR** [comment]
What about calling Observable.StartAsync?

    Observable.StartAsync(async () {
        // not asynchronous code
        await SomeAsync();
    }

or:

    Observable.StartAsync(SomeAsyncMethod);

**Comment by dsuryd** [comment]
New APIs to simplify asynchronous programming inside view models: https://github.com/dsuryd/dotNetify/releases/tag/v4.1.
