### ISSUE TITLE
Using an Async method in AddProperty.SubscribedBy()

### ISSUE THREAD

**Issue by debuggingmyhead** [dsuryd/dotNetify#112]
Hello,

I have another async question. I'm trying to do the following:

```csharp
public MyViewModel() {
...
    AddProperty<FormData>("Login")
        .WithAttribute(new {Label="Sign in"})
        .SubscribedBy(
            AddProperty<string>("ServerResp"), async input => await Login(input));
}

async Task<string> Login(FormData input) {
    var resp = await _someService.SomeAsyncMethod(input);
    return resp.Message;
}
```

When I try to do the above I have an issue, which is that the overload for SubscribedBy() that uses IObservable<> gets called. If I try to change the Login method to return and or accept IObservable<> then I run into other issues (I can go into more detail if needed).

I suspect I am simply not understanding something or doing something wrong (i.e. I cannot call an async method in SubscribedBy).

Any help is appreciated.

**Comment by dsuryd** [comment]
`SubscribedBy` won't work with async functions; you'd need to use the `Subscribe` method:
```csharp
   var serverResp = AddProperty<string>("ServerResp");

   AddProperty<FormData>("Login")
      .Subscribe(async formData =>
      {
         serverResp.Value = await Login(formData);
         PushUpdates();
      });
```

**Comment by debuggingmyhead** [comment]
Makes sense. Thanks for the help!
