### ISSUE TITLE
Redirect to component

### ISSUE THREAD

**Issue by debuggingmyhead** [dsuryd/dotNetify#113]
I'm trying to code a simple redirect and having some issues. I'm testing a login page and after the form successfully submits, in my onStateChange handler (I'm using dotNetify Elements) I have the following code:

```javascript
DotNetify.react.router.redirect('TestPage');
```

This updates the browser's url bar and also seems to reload the component, but it ends up just refreshing the current Login page.

I have the "TestPage" route mapped in my Login ViewModel like this:
```csharp
this.RegisterRoutes("index", new List<RouteTemplate>
{
      new RouteTemplate("TestPage", "../lib/components/test/TestPage.js")
});
```

I've tried different module url paths too thinking that may be the issue. Is the path relative to the index.html page and am I correct in thinking that it should be pointing to the wwwroot js file? (On a side note, how would you go about loading a module that is part of the bundle.js file?)

Any help is appreciated.

**Comment by dsuryd** [comment]
The path is resolved at runtime, therefore the fiile must be under wwwroot.  If the path is omitted, the router will look for the component in  _window_ variable.  That's why in the dotNetify-Element's SPA template, the first thing main.js does is to add routable components into _window_.

**Comment by debuggingmyhead** [comment]
Thanks for the reply, I was able to get it working. Forgive me for not checking the SPA template, I started looking through your code and now a lot of things make more sense!

**Comment by dsuryd** [comment]
Thank you for trying Elements out!  please let me know if there's anything in the documentation or the code that can be improved.
