### ISSUE TITLE
Not compatible with react native

### ISSUE THREAD

**Issue by Epicurean** [dsuryd/dotNetify#114]
The signalR client library is not the correct version. As such the following issue has not been fixed:
https://github.com/aspnet/SignalR/issues/2412

This makes using your library with react native impossible

Thanks

**Comment by dsuryd** [comment]
Which version the fix is in: 1.0.3 or 1.1.0-preview1?

**Comment by Epicurean** [comment]
The fix seems to be in 1.0.3

**Comment by dsuryd** [comment]
Just published dotNetify v3.0.2 that has SignalR client v1.0.3.
