### ISSUE TITLE
Possible issue with routing and React bundle.js

### ISSUE THREAD

**Issue by debuggingmyhead** [dsuryd/dotNetify#116]
Hello,

I'm having an issue but it's possible it's not directly related to dotNetify and could be a general React issue that I need to address. I'm still new to all of it so I'm not sure...

I'm using Elements and I have a working NavMenu that updates the NavMenuTarget perfectly. There are currently two nav items for Dasboard and User Management.

My issue is with direct routing. If I directly navigate to mysite.com/dashboard it works as expected, but if I navigate to mysite.com/users/manage it fails (again, it works when navigated to via the NavMenu).

In my troubleshooting it seems the issue is that React is loading the bundle.js file from mysite.com/users instead of the root of mysite.com (where it lives). So, it seems to think the /users part is part of the root url.

Do you think this is related to the dotNetify router logic? Or perhaps how my routes are defined in my view models? 

Any help is appreciated. Let me know if you need more specific info about my project or if this actually is not a dotNetify issue.

*Edit*
I realized this additional info might be helpful: There are 3 components right now, App, Dashboard, and UserManagement. The NavMenu routes are defined in the top level App component with the root set to "". For user management, I have the url pattern set to "users/manage". Should I be registering that route under the root of "users" with the url pattern as just "manage"?

Should I not be defining all the nav menu routes at the top level, but instead in their respective View Models, and then using the Redirect api when create the NavMenu property?

**Comment by dsuryd** [comment]
Your setup seems fine.  Could you paste the route registration code?

**Comment by debuggingmyhead** [comment]
```csharp
this.RegisterRoutes("", 
     new List<RouteTemplate>
            {
                new RouteTemplate("Home") { UrlPattern = "", ViewUrl="Dashboard" },
                new RouteTemplate("Dashboard") { UrlPattern = "dashboard" },
                new RouteTemplate("UserManagement") { UrlPattern = "users/manage" }                             
            };
```

**Comment by dsuryd** [comment]
I was able to use the same URL pattern without issue.  I started from the SPA template (`dotnet new elements)`, and then replaced the last page's URL pattern to "users/manage".   It navigated correctly from the browser's address bar.   

Perhaps it's how you specify the bundle path in your `index.html`.   Make sure it starts with "/".

**Comment by debuggingmyhead** [comment]
Yup, the bundle path didn't start with "/". Adding that solved it.

Can't believe I didn't catch such a dumb mistake :expressionless:  
Thanks for taking the time to help!!
