### ISSUE TITLE
[Elements] I'm not able to execute a simple action when a button inside a Form is clicked

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify#117]
This samples works properly for me without problems. However when I try to add a button that executes an action in the viewmodel I don't manage to get it done:

```
[React]
...
<Button label="Next" id="Next" show={!edit} />
...

[VM contructor in C# Alternative 1]
...
AddProperty<object>("Next")
                .Subscribe(_ => LoadFormWithNextItemAsync().GetAwaiter().GetResult());
...                

[VM contructor in C# Alternative 2]
...
AddProperty<object>("Next")
                .SubscribedBy(AddProperty<bool>("NextSuccess"), _ => LoadFormWithNextItemAsync().GetAwaiter().GetResult());
...
```
For anyone of these two alternatives it does nothing. I use dotnetify.debug=true in React Code but after the click there is not any tranmision of data. I set a breakpoint int the body of the lambda but it never stops there so no calls to `LoadFormWithNextItemAsync().GetAwaiter().GetResult()`

Any idea of what am I doing wrong?

**Comment by jersiovic** [comment]
No, when the button is clicked no data is sent. Data is only sent when the page is loaded.
This is the data sent when page is loaded, ¿is it normal Next value is null there?
![image](https://user-images.githubusercontent.com/4950766/45827558-f6990400-bcf6-11e8-93af-ba2a002bd02f.png)

**Comment by dsuryd** [comment]
The problem must be somewhere in the React code.  Can you paste yours, or compare it with this working snippet:

```jsx
import React from "react";
import dotnetify from "dotnetify";
import { Button, Panel, VMContext, withTheme } from "dotnetify-elements";

dotnetify.debug = true;

class Test extends React.Component {
  render() {
    return (
      <VMContext vm="Test">
        <Panel>
          <Button label="Next" id="Next" show={true} />
        </Panel>
      </VMContext>
    );
  }
}

export default withTheme(Test);
```

```csharp
using System;
using System.Reactive.Linq;
using System.Threading.Tasks;
using DotNetify;

namespace spa_template
{
    public class Test : BaseVM
    {
        public Test()
        {
            AddProperty<object>("Next")
            .SubscribedBy(AddProperty<bool>("NextSuccess"), _ => LoadFormWithNextItemAsync().GetAwaiter().GetResult());
        }

        private async Task<bool> LoadFormWithNextItemAsync()
        {
            return await Task.FromResult(true);
        }
    }
}
```

On load this outputs:
![image](https://user-images.githubusercontent.com/14990482/45829654-499b9880-bcb0-11e8-89c5-691a833e4685.png)

And when the button is clicked, it outputs:
![image](https://user-images.githubusercontent.com/14990482/45829700-5ddf9580-bcb0-11e8-9366-2ad3dd80b3f1.png)

**Comment by jersiovic** [comment]
Thank you, I've found the issue only happens when Panel is within a Form.
```
class FamilyForm extends React.Component {
    
    render() {
        
        return (
            <VMContext vm="FamilyVM">
                
                <Form>
                    {/* Toolbar */}
                    <Panel>
                            <Button label="Next" id="Next" show={true}  />
                    </Panel>
                </Form>
            </VMContext>
        );
    }
};
export default withTheme(FamilyForm);
```
Removing Form element it works properly
```
class FamilyForm extends React.Component {
    
    render() {
        
        return (
            <VMContext vm="FamilyVM">
                
                    {/* Toolbar */}
                    <Panel>
                            <Button label="Next" id="Next" show={true}  />
                    </Panel>
            </VMContext>
        );
    }
};
export default withTheme(FamilyForm);
```

**Comment by dsuryd** [comment]
Thanks, this is a bug.  The Form element should've let the button click goes through.

**Comment by jersiovic** [comment]
Moving button out of the form method on viewmodel is called. But now I've found another problem.

It looks that updates are not pushed to client when different threads change the state of the viewmodel on server side.

If I have an await for and async method accessing db before setting values to state, changes done to state are not reflected on the view cause changes are done by another thread. You can emulate that with await Task.Delay().

This works properly:
```
            VMTitle = $"Family: {contador++}";
            PushUpdates();
            await Task.Delay(100);
```
This doesn't work properly:
```
            await Task.Delay(100);
            VMTitle = $"Family: {contador++}";
            PushUpdates();            
```
Is there a way of delegating the update of the state to the original thread ( acting as a kind of "UIThread")?
Or it sth to investigate and I should file a new issue with that?

**Comment by dsuryd** [comment]
Let's discuss as a separate issue.   This is a similar topic to #110, but I couldn't reproduce the problem you're seeing.  `PushUpdates()` works on any thread.   

Below is what I tried that works.  If I have to guess, you only implemented `VMTitle` as auto-property?  If so, then you need to explicitly called `Changed(nameof(VMTitle)))` in the async scenario.

```csharp
public class Test : BaseVM
{
    public string VMTitle
    {
        get => Get<string>();
        set => Set(value);
    }

    public Test()
    {
        AddProperty<object>("Next")
            .Subscribe(_ => Task.Run(async () => await RunAsync()));
    }

    private async Task RunAsync()
    {
        await Task.Delay(100);
        VMTitle = DateTime.Now.ToString();
        PushUpdates();
    }
}
```
