### ISSUE TITLE
Qt QML Websocket client support

### ISSUE THREAD

**Issue by antonyrey** [dsuryd/dotNetify#119]
Hi,

First thanks a lot for this amazing library !

We use it within an electronjs+Reactjs application and it's amazing.

We would like to know if porting to Qt QML with the Websocket (https://doc.qt.io/qt-5/qml-qtwebsockets-websocket.html) component would be an option ? (using pure QML / javascript)

This would allow developers to have a QML UI connected to a C# backend.

Thank you, have a nice day ;-)

**Comment by dsuryd** [comment]
Thanks, it's very encouraging to hear success stories!  
Porting is always an option, but with my current capacity,  I can only offer limited support for anybody who wants to take on things outside the roadmap.  The websocket part could be a lot of work, since the messaging needs to follow SignalR protocol.

**Comment by dsuryd** [comment]
I have no experience with Qt QML, and if you would enlighten me, what kind of use cases that it excels at?

**Comment by antonyrey** [comment]
Qt Quick (QML) is great when you are looking for high-performance cross-platform software development, especially on embedded devices where performance with limited resource and power is a concern.

We've been developing our business logic in a C# .net standard 2.0 assembly, we use Electron + ReactJS as our UI engine, and Dotnetify is the glue between the business logic layer and the presentation layer.

We are looking for better UI performance and Qt seems to be the best candidate, but we would like to use the C++ side only as a QML host (like electron does with web content) with really little logic, and take advantage of our existing C# layer.

I have heard SignalR Core supports bare websocket incoming connections but i can't find more documentation about it.


Thanks !

**Comment by tw-bert** [comment]
@antonyrey Very good and compact summary. I haven't used Qt in a while, and can't really help out here, but would be very interested in the "bare websocket" part.

**Comment by antonyrey** [comment]
I made some progress about the websocket part, i'm now able to communicate with the dotnetify hub.

Here is how i did : 

- POST http://localhost:5000/dotnetify/negotiate 

- when i get the answer, i can open a websocket with the following url : ws://localhost:5000/dotnetify?id={connectionId}

{connectionId} is retrieved from the POST response, a json object containing a root property named "connectionId"

- i can then communicate : 

 ```
websocket.sendTextMessage(JSON.stringify({ protocol: "json", version: 1 }) + '');

				websocket.sendTextMessage(JSON.stringify({
					arguments: ['StartupPageViewModel', {}],
					invocationId: '0',
					target: 'Request_VM',
					type: 1
				}) + '');
```

I'm helping with chrome network traces : 

![image](https://user-images.githubusercontent.com/167333/46090914-fcd52780-c1b1-11e8-8bd5-5e5096c222ca.png)

**Comment by dsuryd** [comment]
Since QML integrates with Javascript, shouldn't it be possible to just use SignalR Javascript client?

**Comment by antonyrey** [comment]
There are differencies between Qt QML javascript environment and browser environment. There is no window or document object, no setTimeout function, etc...

**Comment by dsuryd** [comment]
With the new dotNetify .NET client combined with [Qml.Net](https://github.com/qmlnet/qmlnet), I think you can now get your QML UI talking to the C# back-end.   I will close this issue, unless you have other considerations.
