### ISSUE TITLE
Cookie Authentication

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#12]
I am not sure if this is the right place to ask, but do you have an example of a simple Authentication option with the users stored in a database or a file? In the App-Template you used the google Authentication, but I would need a custom Authentication with Authorize control of specific html pages.  Maybe you can point me in the right direction.

**Comment by dsuryd** [comment]
Hi, you can use OWIN cookie authentication.  Check this out: https://brockallen.com/2013/10/24/a-primer-on-owin-cookie-authentication-middleware-for-the-asp-net-developer/.

**Comment by DG4ever** [comment]
Thanks for the Infos, I got the authentication working with the Controller and Routing to a Login Page but is there a way to access the current user in the viewmodel? I already saw the AuthorizeAttribute but I have no Idea how to make use of it. 

I am quite new to Web Development as I mostly developed UIs with wpf and the mvvm principle. That's the reason I am using dotnetify as it really simplifies a lot of things.

**Comment by dsuryd** [comment]
The AuthorizeAttribute adorns the view model, for example these will prevent users not in administrator role to access VM1, and users whose custom claim "MyGroup" not equal to XYZ to access VM2.

```
[Authorize(Role="Administrator")]
public class VM1: BaseVM
...

[Authorize(ClaimType="MyGroup", ClaimValue="XYZ")]
public class VM2: BaseVM
...
```

However, this doesn't restrict the initial html page get, so I suggest that at your controller's action method, get the user object directly from OWIN (Request.GetOwinContext().Authentication.User) and perform the authorization control there, whether to return the requested html or to redirect.

**Comment by DG4ever** [comment]
Sorry that I have to bother you again but I have another question. 
Might it be possible to access the current user inside a viewmodel derived from BaseVM?

**Comment by dsuryd** [comment]
No bother at all.  A view model can access the current user context through System.Threading.Thread.CurrentPrincipal.  If this isn't sufficient, we can further discuss.

**Comment by DG4ever** [comment]
Unfortionatly the Identity of CurrentPrincipal is always empty.

I am authentificating in a controller action like this:

`var claims = new List<Claim>();
claims.Add(new Claim(ClaimTypes.Name, CurrentUser.UserName));
claims.Add(new Claim(ClaimTypes.Sid, CurrentUser.UserLevel.ToString()));
var id = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);
authentification.SignIn(id);`

I can access the current Identity in the controller at any time with `ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;` which is working fine.

In the Viewmodel I am using:

`ClaimsIdentity claimsIdentity = (ClaimsIdentity)System.Threading.Thread.CurrentPrincipal.Identity;
				UserName = claimsIdentity.Name;`

But the UserName is always empty. Do you have any idea what I might do wrong?
