### ISSUE TITLE
Dublicate classes issue

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify#121]
Nuget installed packages
`  <package id="DotNetify" version="1.2.0" targetFramework="net471" />
  <package id="DotNetify.Core" version="3.0.1" targetFramework="net471" />
  <package id="DotNetify.Elements" version="0.1.0" targetFramework="net471" />
  <package id="DotNetify.SignalR.Owin" version="3.0.1" targetFramework="net471" />
`

I get odd error after installing dotnetify.elements like I am hitting into a refactoring of code and I am unsure which one to favor (DotNetify 1.2.0 Nuget and DotNetify 1.3.0 in assembly

> The type 'BaseVM' exists in both 'DotNetify, Version=**1.3.0.0,** Culture=neutral, PublicKeyToken=null' and 'DotNetifyLib.Core, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null'

and more oddly this

> The call is ambiguous between the following methods or properties: 'DotNetify.AdapterExtension.UseDotNetify(Owin.IAppBuilder, System.Action<DotNetify.IDotNetifyConfiguration>, DotNetify.IServiceProvider)' and 'DotNetify.AdapterExtension.UseDotNetify(Owin.IAppBuilder, System.Action<DotNetify.IDotNetifyConfiguration>, DotNetify.IServiceProvider)'

**Comment by dsuryd** [comment]
Dotnetify 1.2.0 is an old nuget package, you should uninstall it.

**Comment by larsbuch** [comment]
Old code is never good. Fixed both.
