### ISSUE TITLE
Error in IE ver 11

### ISSUE THREAD

**Issue by benjaminthedonkey** [dsuryd/dotNetify#122]
Hi

Thanks for sharing this project, it's pretty cool, I have a question. The  [SPA Example](https://github.com/dsuryd/dotNetify/tree/master/Demo/React/SPA) dosen't seem to be working in IE  

IE  ver 11 , Error:  Object doesn't support property or method 'assign'.  

This is the line that throws the exception:

```javascript
module.exports = Object.assign(_dotnetifyReact2.default, { Scope: _Scope2.default, RouteLink: _RouteLink2.default, RouteTarget: _RouteTarget2.default });
```

Thanks!

**Comment by dsuryd** [comment]
It needs polyfills; add this to index.html:
```html
<!-- Polyfills for IE 11 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fetch-polyfill@0.8.2/fetch.min.js"></script>
```

**Comment by benjaminthedonkey** [comment]
Works like a charm, thanks.   Looking forward for the MulticastVM, all good stuff...
