### ISSUE TITLE
Redux state philosophy 

### ISSUE THREAD

**Issue by benjaminthedonkey** [dsuryd/dotNetify#123]
Thanks again for this amazing library.  I have a question, I noticed that in your examples you update the view state before calling the method $dispatch. But the state will be updated as a result of the round trip: client -> server -> client right ?.   
I'm a big fan of the Redux library philosophy of having a read-only state on the client side and enforcing that every change is submitted as an action. This has many advantages.  I think DotNetify could easily provide methods to facilitate this design pattern.  For example, having a method in the view model that returns the last N Actions on the state.... this would also make an "undo" mechanism easy to implement. 

Thanks.

**Comment by dsuryd** [comment]
Optimistic update is the reason for view state update.  If the client-side state update must wait for its server, on high latency network your web app would appear sluggish.  

With that said, I do like Redux concepts of single source of truth and controlled mutation; it is quite compatible with Reactive programming.  The question is, where will that single source of truth reside? And it's going to have different answers for different applications.

The way I see it, if latency isn't a problem, you could implement server-side Redux with what dotNetify offers today, predicated on having a Redux store as a separate, injectable abstraction.  A redux view model will have state properties that subscribe to the store, and action properties that the store subscribes to.  Its view can only dispatch actions, which then goes on a cycle, through the store and its reducers, back as state update to the view.

**Comment by dsuryd** [comment]
Marking this as enhancement to explore the possibility to have a redux-like abstraction to support undo mechanism.

**Comment by jzabroski** [comment]
Why not have a bridge layer in JS to catch the stream and write to Redux the "events"?

**Comment by dsuryd** [comment]
More desirable to have it on the server-side as is the premise of this library, especially with multicasting.

**Comment by lilasquared** [comment]
@dsuryd I just read through this and after working on the react-hooks I was surprised to see that the client->server->client round trip did NOT update the state of the properties I was manipulating.  In the very simple HelloWorld example, when `FirstName` is updated and dispatched to the server, the server response only contains the `FullName` Property.  In a multi cast VM, both properties were sent to each connected client **EXCEPT** the client who made the update.  It seems the client side state update is required to keep in line with the server at this time.  If the server were to act as a "redux" type of state then I would expect the response would need to contain all updated properties even to the client who made the update.  Thoughts?

**Comment by dsuryd** [comment]
@lilasquared The library doesn't make assumption on what should/shouldn't be sent back to the client, leaving it up to the developer to be explicit by calling `Changed`, or `Set` which internally calls it (the only exception is, for efficiency sake, it prevents the dispatching client from getting back the same property it dispatched if the value's unchanged.)  In other words, it's agnostic to where the source of truth is.

In the context of server-side redux, I agree with you that all updated properties must be sent out since the server state becomes the single source of truth.  But then, the client won't be dispatching mutated properties, only actions, e.g. `vm.$dispatch({'SetFirstName': 'fname'}` so it won't be a problem.

**Comment by lilasquared** [comment]
So as long as I dispatch actions to the server then it will return all changed property values. That makes sense.

**Comment by dsuryd** [comment]
I'm closing this since redux state management doesn't seem to belong in the core library, and there are already other open source .NET libraries providing redux implementation (redux.NET, Fluxor ) that probably can work well with dotNetify.
