### ISSUE TITLE
Provide initial state from React Component to View Model

### ISSUE THREAD

**Issue by illumen** [dsuryd/dotNetify#125]
Hi,

Is it possible to provide the view model with an initial state from the react component?

I tried doing;
```javascript
 let initialState = { TestVar: "Hello" };
 dotnetify.react.connect("HelloWorld", this, {vmArg: initialState});
```

```csharp
public class HelloWorld : BaseVM
{
   public string TestVar { get; set; }
   public HelloWorld() {
      Console.WriteLine(this.TestVar);
   }
}
```

TestVar is still null here...

// Regards

**Comment by dsuryd** [comment]
Properties cannot be externally initialized before object construction.  It happens right after.

**Comment by dsuryd** [comment]
Closing this as there's no follow-up question.  Refer to the linked issue above  for example on how to initialize the VM properties given the initial state from the client.
