### ISSUE TITLE
Accessing groups and users

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify#128]
It would be nice to have an example of how to access SignalR Clients and Groups either from Middleware or from VM

**Comment by dsuryd** [comment]
Take a look at the MulticastVM API doc and the Chat Room example.

**Comment by bugged84** [comment]
@larsbuch here are links for [MulticastVM API](http://dotnetify.net/core/api/multicast) and the [Chat Room example](https://github.com/dsuryd/dotNetify/blob/master/DevApp.ViewModels/Examples/ChatRoom.cs)

**Comment by bugged84** [comment]
I was hoping that maybe when configuring a `RouteTemplate` I could set the `UrlPattern` property to something like "chat/{id}" and then define an `id` parameter on the constructor of the `ChatRoomVM` in order to be passed the room identifier for a requested URL such as "chat/5". Then the view model could use this value to generate the group name for partitioning.

**Comment by larsbuch** [comment]
I have been looking at the MulticastVM/BaseVM and Chat Room examples. I have not found it in either.

@bugged84 : It is not nice to make issue hijacking for irrelevant information. Normally you should open a new issue for the discussion.

**Comment by dsuryd** [comment]
@larsbuch: I may not be understanding you; what kind of example you're looking for?  MulticastVM provides a `Send` method to send message to any SignalR clients and groups.    For direct access to SignalR APIs, inject their `IHubContext` as documented in SignalR website.

@bugged84: Please create a new issue for us to discuss on how to implement group chat rooms.

**Comment by larsbuch** [comment]
I will go forward with that as well

**Comment by bugged84** [comment]
@dsuryd do you have an example of the `MulticastVM` `Send` method that you referred to above? Does the second argument `propertyName` refer to the name of a property on the React component's state object?

**Comment by bugged84** [comment]
I set `propertyName` to "hello" and `propertyValue` to "world" and the following was logged in the browser console.

```
[ChatRoomLobby] received>
{hello: "world"}
```

What can be done with this? For example, what if I want the React component to display the value of the `hello` property? How can this be done?

**Comment by dsuryd** [comment]
The chat room example uses the `Send` method to send private message to chat users.
