### ISSUE TITLE
Trouble with my move event

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#130]
Hi Dicky:
I am having trouble with my event. When I try to raise it, I receive a "Cannot access a disposed object" exception. Any clues?

**Comment by mojo-man** [comment]
Here is the declaration:
		private readonly ReactiveProperty<moveData> _moveVisitEvent;

Here is the beginning of the constructor:
		public DisplayManager()
        {

            Console.WriteLine("Constructor Begin");

			_openVisitEvent = AddProperty<moveData>("openVisitEvent");
			_moveVisitEvent = AddProperty<moveData>("moveVisitEvent");
			_closeVisitEvent = AddProperty<moveData>("closeVisitEvent");
			_visitorSnapshotEvent = AddProperty<List<VisitorSnapshot>>("visitorSnapshotEvent");

And - here is where I am encountering the exception:
                case "VISIT.MOVE.EVENT":
					// cast to a move message
					var msgMove = (VisitMoveMessage)visitMsg;

                    try
                    {
						// send the move event to the front-end
						var md = new moveData(msgMove.VisitId, msgMove.FromId, msgMove.ToId);
						_moveVisitEvent.OnNext(md);
					}
                    catch (System.Exception ex)
                    {
						Console.WriteLine("Exception encountered [VISIT MOVE EVENT]: {0}",ex.Message);
					}
                    break;

**Comment by dsuryd** [comment]
Something must've gotten disposed - are you sure the VM instance is still around when that call is made?  What does the call stack look like?

**Comment by mojo-man** [comment]
Here is what the call stack looks like:
```
   at System.Reactive.DisposedObserver`1.OnNext(T value)
   at DotNetify.ReactiveProperty`1.OnNext(T value)
   at HME.Timer.Display.DisplayManager.ProcessVisitMessage(IMessage visitMsg) in C:\Content\Data\Dev\Janus\DisplayServer\DisplayServer\DisplayManager.cs:line 166
```

**Comment by mojo-man** [comment]
It's possible that my react client isn't accessing things properly though... what actually instantiates the VM?

**Comment by mojo-man** [comment]
Current react instantiation:
```componentDidMount() {

        var arg = { User: { Name: "Joe" } };
        this.vm = dotnetify.react.connect("DisplayManager", this, { vmArg: arg });
```

**Comment by mojo-man** [comment]
Nevermind Dicky - It turns out it was a threading issue. Yuck!

**Comment by mojo-man** [comment]
Do I still need PushUpdates() ?

**Comment by dsuryd** [comment]
Use `PushUpdates` if it's server-initiated push.

**Comment by mojo-man** [comment]
Yes - I am generating the event from my c# code - event makes it to the react front-end, but there are no props showing up in nextState

**Comment by dsuryd** [comment]
Server-originated data would be inside state, not props.

**Comment by dsuryd** [comment]
The fact that `shouldComponentUpdate` is called means either prop or state has changed.  I ran my own test here, and worked as expected.  If you're really stuck, I can help you better if you create a small dotnet .csproj that demonstrates the problem.

**Comment by mojo-man** [comment]
How can I send you some code to look at?

**Comment by dsuryd** [comment]
Just send me a link to your public repo/cloud service.

**Comment by mojo-man** [comment]
It isn't public Dicky - You are on my LinkedIn - could you call or email?  https://www.linkedin.com/in/dvallen1/

**Comment by dsuryd** [comment]
I do not want to see your company’s source code; just create a generic
project, preferably from dotnetify demo template that you modify to
demonstrate this particular problem.

And if I have to call or email you privately, I will probably need to
charge you for support 🙂

**Comment by mojo-man** [comment]
I just sent you an email from my work account.

**Comment by mojo-man** [comment]
Thanks so much for sending the code example. Everything in the HelloWorld.cs code looked similar to mine - although I did wonder if the PushUpdates() was required when using events. Apparently it is. In the HelloWorld.js code, I noticed that you had the dotnetify.react.connect statement in the constructor. We had ours in the componentDidMount event. I moved it - but there was no improvement.

**Comment by mojo-man** [comment]
Also - my code is running from npm start (using concurrently) not from dotnet run. Does this seem workable to you - or could that be a part of the problem?

**Comment by dsuryd** [comment]
How it starts shouldn't matter.  Can you make your React component very simple, just like that HelloWorld sample, but leave the view model untouched.  Assuming you already set `dotnetify.debug = true`, add console logs to componentDidMount, componentDidUpdate, and shouldComponentUpdate:
```jsx
componentWillMount() {
   console.log('componentWillMount:', this.state);
}

componentDidMount() {
   console.log('componentDidMount:', this.state);
}

shouldComponentUpdate(props, state) {
  console.log('shouldComponentUpdate', props, state);
}

componentDidUpdate(props, state) {
console.log('componentDidUpdate:', props, state);
```

Run the event, and show me the screenshot of the console log output.
Also, check whether there are console errors.

**Comment by mojo-man** [comment]
Thanks for the advice. I will make a simple react component today to test my code with.
