### ISSUE TITLE
Difference between BaseVM and MulticastVM

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#134]
Can you please help me understand the difference between the BaseVM and the MulticastVM? I'm not certain which to use? I want to be able to support multiple clients connection to the same VM - sharing the same state (if possible). Your chat room illustrates that use case beautifully, but each client - in my use case would be displaying an identical dashboard.

**Comment by dsuryd** [comment]
MulticastVM is exactly what you said - same VM instance shared among multiple connections.
