### ISSUE TITLE
Bind to Subclass

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#14]
Is it possible to bind to a subclass?
I would like to create a base class for my pages as they all have some basic features.

I tried something like this:

`public class PageBase : BaseVM, IRoutable`

`public class Page1 : PageBase `

Unfortionatly it doesn't seem to work when I bind to Page1. Is dotnetify only looking for classes which are directly based on "BaseVM"?

**Comment by dsuryd** [comment]
I use subclasses in the composite view example.  Do you see errors logged in the browser? (set dotnetify.debug to true to see it)

**Comment by DG4ever** [comment]
Thanks I got it working. Not sure what I did wrong last time, now everything works as expected.
