### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by stevehayles** [dsuryd/dotNetify#142]
Hi,

Loving the new Vue version, you have gone way beyond an initial look at it and it feels very thorough. 

Just followed the instructions through (just to learn by building from scratch) and I noticed a small omission in the Vue docs.  Might trip someone up

In the [http://dotnetify.net/core/fromscratch-webpack](url) page the webpack.config.js snippet is not quite complete

**Comment by dsuryd** [comment]
Thank you, will take a look at it!
