### ISSUE TITLE
(Question) Sending Non-state data

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify#144]
I have data that needs to be generated on the server depending on user, database and server settings at runtime. I do not need to be able to send it back to the server as it already have the information. 

I know that I can use/misuse the MulticastVM for serverwide settings which covers the runtime database and server settings.

I do not have a nice way to do this for user data. I would like to have it outside the state object where I right now have it as the normal way to dispatch to the server is to send the whole state object.

Is there a nice way to do this ?

**Comment by dsuryd** [comment]
Sorry, I don't really follow.  Concrete example would help.

**Comment by larsbuch** [comment]
I have several types of data that the UI needs from the server. I am here
only thinking on the non-admin parts of a website. I would like to have one
way to handle non-static data whether it is readonly or not.

- Static data that follows website version such as CSS, images, React
components etc. This is not a problem as it is standard website.

- Semi-Dynamic data related to current server state and configuration. It
could be handled by the MulticastVM without updatable functions so it in
effect is converted to a read-only VM. Current VMs expect set functions and
that it can be sent to server. Because it is readonly it pollutes the
normal state/VM. This is also common for a large amount of users and
components. This can be changed in the admin section by admin users.

- Dynamic data related to current server state and configuration and user
settings such as drop-down options and FSM data for components. Again this
is readonly data. This would polute the normal state/VM.

- Dynamic data that translates to state in React components and should be
updatable on the server.

It is the readonly VM parts that breaks the MVVM style in DotNetify. I was
thinking if I needed to make two readonly versions of the VMs to handle the
dynamic and semidynamic readonly data and use a subVM for the actual
updatable state.



man. 12. nov. 2018 19.07 skrev Dicky Suryadi <notifications@github.com>:

**Comment by dsuryd** [comment]
Have you considered using a custom middleware to inject the data to the outgoing response JSON?

**Comment by larsbuch** [comment]
Not really. That would make it read only for sure but it would still mean I
need to rewrite the receiving JavaScript to avoid it going into the state.
I might need to do that anyway to support TypeScript.

I have been thinking of adding a read-only attribute or an entire readonly
VM but again a rewrite of the receiving JavaScript.

I am thinking to dive into the JavaScript as I think I need to do that
anyway.

ons. 14. nov. 2018 19.00 skrev Dicky Suryadi <notifications@github.com>:

**Comment by dsuryd** [comment]
If there's nothing else, I am closing this one.  To conclude, two options to consider: 1) use masterVM/subVM, or 2) use middleware.   Feel free to reopen if you have other suggestions.
