### ISSUE TITLE
Typescript definition files:  hubPath, debug, debugFn missing

### ISSUE THREAD

**Issue by treg** [dsuryd/dotNetify#145]

**Comment by dsuryd** [comment]
Would you like to do a PR?

**Comment by 7thcubic** [comment]
Am trying to look into populating the typescript, but i cant seem to find the files on the git. either i am blind, or it isnt there??

It should be in DevApp/src/dotnetify/typings right?!?

**Comment by dsuryd** [comment]
You're right; the folder accidentally wasn't transferred to the master branch from [v3.0 branch](https://github.com/dsuryd/dotNetify/tree/v3.0/src/typings).  If you want to correct this, I'll wait for your PR.  Thanks!
