### ISSUE TITLE
How to send data to the specified person, and how to get the data from the C# client to the server.

### ISSUE THREAD

**Issue by qcjxberin** [dsuryd/dotNetify#147]
How to send data to the specified person, and how to get the data from the C# client to the server.

**Comment by dsuryd** [comment]
Your question is too open-ended, you need to be more specific.  There are plenty of examples in the website that can guide you; the closest to what you're asking is the chat room example.  

There's no C# client yet; it's in progress, but I can't give firm date when it'll be done.  Keep watching this repo!

**Comment by qcjxberin** [comment]
I hope that the C# client version will be as soon as possible, we have such a need to interact with the data passed by the hardware.

**Comment by dsuryd** [comment]
I am closing this; use issue #102  to track the C# client support.
