### ISSUE TITLE
SPA needs ~4s to load on mobile devices

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#15]
Is there a reason, why mobile devices are really slow in loading the website?

I have got a SPA that has several nested pages.  When it is initally loaded, or when I press reload, it needs 4s to render the content on mobile devices. But once it is loaded, I can switch in under <1s between the nested pages. 

On a desktop pc the page is always loaded in <1s.

**Comment by dsuryd** [comment]
The only time I see initial significant loading delay is when using ASP.NET Core web server on non-WebSocket connection, which isn't seen with ASP.NET 4.5.  This seems an issue of SignalR for .NET Core (which is still alpha).   But if you're still on 4.5, it probably has something to do with your environment setup.  I'll need more details from you - what web server, which mobile device, which browser and version, what's the OS version etc.   The WebStore example in the live site dotnetify.net is probably close to what you're developing.  Try the site from your mobile device, both book (server-side routing) and music (client-side routing).  Do you see similar slowness?   My own test on several mobile devices do not see any slowness.  I also have Cordova app from dotnetify-app-template github deployed on my iPhone SE iOS 10.2 and connecting to my local web server over Wifi, and it goes smoothly too.

**Comment by DG4ever** [comment]
I am using IIS and ASP.NET 4.5

But I think it has nothing to do with my setup as it behaves exactly the same on your Webstore example.

I have screen recorded the behavior and on both, books and music category, it needs 7s! to reload the page. However when switching between books and music it is fast as expected.
I tested it with a Note 4 and with an iPhone 6 with the same results.
On a desktop machine it only needs <1s to reload the pages.

Here is the video:
https://youtu.be/iW6elFH_bqc

**Comment by dsuryd** [comment]
Could you try this.  In your dotnetify.js, find:
`var hub = $.connection.hub.start();`
and replace it with:
`var hub = $.connection.hub.start({ "transport": ["webSockets", "longPolling"] });`

If delay is still seen, remove the` "webSockets"` and retry.

**Comment by DG4ever** [comment]
`var hub = $.connection.hub.start({ "transport": ["webSockets", "longPolling"] });`
Thanks great, that did it. Now the reload is <1s.

**Comment by dsuryd** [comment]
With new version 1.1.2, setting transport can be done outside of dotnetify.js.  Add this to app.js:
```
require(['signalr-hub'], function () {
   dotnetify.hubOptions = { "transport": ["webSockets", "longPolling"] };
});
```
The delay seems to be caused by signalR switching to serverSentEvent transport, but only some cases.  Definitely aim for your IIS to support websockets connection rather than letting clients fall back to longPolling.

**Comment by DG4ever** [comment]
Good to know, thanks. I googled a bit and is it correct that there is no websocket support when using Windows 7?

Would a self hosted site with NancyFx be able to use websockets on Windows 7 or do I need Windows 8?

**Comment by dsuryd** [comment]
Yes, it requires at least Win 8.  Here's the official site: https://www.asp.net/signalr/overview/getting-started/supported-platforms
