### ISSUE TITLE
Redirect to a component with URL path parameters

### ISSUE THREAD

**Issue by bugged84** [dsuryd/dotNetify#150]
@dsuryd I found your comments in [this other issue](https://github.com/dsuryd/dotNetify/issues/113), but they don't quite address my scenario. Do you have an example of redirecting to a template such as the one below?

```
this.RegisterRoutes("chat-rooms", new List<RouteTemplate>
{
    new RouteTemplate("ChatRoomList") { UrlPattern = string.Empty },
    new RouteTemplate("ChatRoom") { UrlPattern = "(/:id)" }
});
```

Using a `<RouteLink>` component works fine to route to a chat room from a list of links, but what if I want to redirect the user to a specific chat room based on a message sent from a `MultiCaseVM`?

```
componentDidUpdate() {
    if (this.state.NewChatRoomId) {
        let chatRoomId = this.state.NewChatRoomId;
        dotnetify.react.router.redirect( ??? );
    }
}
```

What should I replace the question marks with?

**Comment by bugged84** [comment]
I see this in the console log when arriving at my landing page.

```
router> map /chat-rooms to template id=ChatRoomList
router> map /chat-rooms(/:id) to template id=ChatRoom
router> routing /chat-rooms
router> route '' to template id=ChatRoomList
router> routed
```

**Comment by bugged84** [comment]
I can make it work with the following.

`window.location.replace("chat-rooms/" + chatRoomId);`

This seems undesirable, though, when I have route templates configured.

**Comment by dsuryd** [comment]
The `redirect` accepts a path.  Try: `dotnetify.react.router.redirect('chat-rooms/' + chatRoomId)`.

**Comment by dsuryd** [comment]
The other way is to use `vm.$routeTo(<route object>)` where <route object> is a predefined object created in the server-side view model using `this.GetRoute(<template name>, <url pattern>)`.

**Comment by bugged84** [comment]
@dsuryd I had tried passing that same path to `dotnetify.react.router.redirect` but the function fails saying that `length` cannot be read on an `undefined` viewModels parameter.

**Comment by bugged84** [comment]
![image](https://user-images.githubusercontent.com/23638686/48958352-fc43dd80-ef23-11e8-8b9b-4be3e20593fb.png)

![image](https://user-images.githubusercontent.com/23638686/48958364-18477f00-ef24-11e8-87df-1baa562a680b.png)

**Comment by dsuryd** [comment]
Now that I thought about it, redirect is more of an internal method, not
meant to be used directly.  Can you try the vm.$routeTo instead.

**Comment by bugged84** [comment]
Not sure `vm.$routeTo` will work for me then, since you said it requires a predefined route object on the view model. My route to a new chat room can't be predefined, as it can't be known until a user creates it at run-time.

**Comment by dsuryd** [comment]
You can create an initial Route object that you store in the component
state.  Then clone the object, modify its urlPattern property to point to
the desired chat room Id , and pass it to vm.$routeTo.

**Comment by dsuryd** [comment]
Closing this as the question has been answered.
