### ISSUE TITLE
What's a good way to detect that a caller has disconnected from a ViewModel?

### ISSUE THREAD

**Issue by bugged84** [dsuryd/dotNetify#151]
I'm trying to detect when users connect and disconnect from my VM. Detecting the connection is easy using the `OnRouted` handler.

```
this.OnRouted((sender, e) =>
{
    var userId = hubCallerContextAccessor.CallerContext.ConnectionId;
	
    // handle user entry
    m_users.Add(userId);
	
    // subscribe to user exit
    m_hubCallerContextAccessor.CallerContext.ConnectionAborted.Register(() =>
    {
        m_users.Remove(userId); // never gets called...
    }    
});
```

However, I'm not able to come up with a reliable way to know on the server when a user disconnects.

Do I have to resort to adding a `KeepAlive` action on the VM that the React component calls on regular intervals, and then the VM removes any user that has not reported in recently?

**Comment by dsuryd** [comment]
Like in the chat room example, make an explicit dispatch from
componentWillUnmount to let the VM knows the user is leaving.  Also for non
websocket connection, handle window before unload event too.

**Comment by bugged84** [comment]
That was one of the options I considered. However, that would not be purely server side detection. For example, what if the user's device suddenly crashes or loses internet? I want the server to be able to detect this and boot the user from the chat room. Depending on a react component for this detection will introduce an unstable chat room. This problem only becomes worse if, for example, you're dealing with a game that has active players.

**Comment by dsuryd** [comment]
I don’t have it off the top of my head, but there could be an event that SignalR provides for such scenario.  Check their doc, then we’ll figure out how to access it from the VM.

**Comment by bugged84** [comment]
SignalR hubs have the following lifecycle methods that can overridden.

```
public override Task OnConnected()
{
    return base.OnConnected();
}

public override Task OnDisconnected()
{
    //custom logic here
    return base.OnDisconnected();
}

public override Task OnReconnected()
{
    return base.OnReconnected();
}
```

**Comment by bugged84** [comment]
Also, apparently the `MulticastVm.Dispose()` method is called each time one of these sudden disconnections happen. I moved my "remove" logic to the `Dispose` method and it seems to be working as expected.

**Comment by dsuryd** [comment]
Yes, of course, that what I should have mentioned to you from the beginning :). Need to put this in the doc.
