### ISSUE TITLE
Send method of MulticastVM not working in the OnRouted handler

### ISSUE THREAD

**Issue by bugged84** [dsuryd/dotNetify#152]
From the [docs](http://dotnetify.net/core/overview):

> ... dotNetify employs something similar to the request-response cycle, but in this case it's action-reaction cycle: the front-end initiates an action that mutates the state, the back-end processes the action and then sends back to the front-end any other states that mutate as the reaction to that action.

I'm trying to do the following, when a user enters the multicast chat room lobby.

```
this.OnRouted(
    (sender, args) =>
    {
        Send(
            new List<string> { connectionContext.ConnectionId }
          , "Welcome"
          , new { Rules = "..." }
        );
    }
);
```

However, I see nothing logged in the browser console like I do when I call `Send` from within an Action handler on the VM (e.g. Submit). Does the `Send` method only work within an action-reaction cycle?

**Comment by dsuryd** [comment]
No, `Send` goes on a separate path from that cycle.  You will need to make the call async to give the chance for the initial VM request to complete first.
