### ISSUE TITLE
Push Data

### ISSUE THREAD

**Issue by quintonv** [dsuryd/dotNetify#154]
Hi,

I would like to push some data directly to the SignalR hub from an external application. What would be the best way as the Hub?

Thanks

**Comment by dsuryd** [comment]
I’m not clear on what’s being asked.  SignalR hub in general or dotNetify
hub?  What kind of external app?

**Comment by quintonv** [comment]
I would like to for example update values to the shared VM from a console
application.

**Comment by dsuryd** [comment]
A C# console app pushing data to a VM running on ASP.NET Core server ?  You will need a dotNetify C# client.  It's not available yet, but it will be soon.

**Comment by quintonv** [comment]
Thanks, I'll wait for the c# client then.
