### ISSUE TITLE
ASP Core js version

### ISSUE THREAD

**Issue by weedkiller** [dsuryd/dotNetify#156]
hi any chance we can get straight asp core version?

**Comment by dsuryd** [comment]
What did you mean by 'straight asp core version' ?

**Comment by dsuryd** [comment]
If I were to create my own client-side library to bind dotNetify view model data to the HTML and use nothing but jQuery and vanilla JS, I would be basically reinventing the same wheel that all those UI libraries already did tremendously well.

I understand that you want to avoid the overhead that come from using a UI framework, and I agree that some, like Angular, do impose a steep one.   But please consider Vue in lieu of jQuery.  It's one of the lightest and easiest-to-learn library especially for .NET developers, and it doesn't require a build tool.  Take a look at this Vue page from the .NET Client demo: [index.html](https://github.com/dsuryd/dotNetify/blob/master/Demo/DotNetClient/AspNetCoreServer/Server/wwwroot/index.html), this script tag is the only thing you need to load Vue, and it's just 42KB.
```
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
```

**Comment by weedkiller** [comment]
I think you missed the point, I was asking about straight ASP MVC core - dont need to reinvent the wheel - just show whats shipped with Visual Studio and MS, and not force new dependencies.

We can choose later
