### ISSUE TITLE
synchronization of data between clients?

### ISSUE THREAD

**Issue by Spongman** [dsuryd/dotNetify#157]
(this is _not_ about `MulticastVM`)

i'm wondering if there's a sample or guidance that covers synchronizing model data between different views on clients. For example, with the live dashboard/form/table example, if i have a client looking at the table view, and another client editing the employees' names in the table view, i would like a way for the changes to appear in the table view - they don't currently. i'm not sure how to hook up property-changed events on the employee model class to the UI.

another example is this: http://dotnetify.net/elements/examples/customerform. open that page in two browsers, edit one of the names in browser 1, browser 2 doesn't update, refresh browser 2 - it updates.

**Comment by dsuryd** [comment]
I don't have any sample for that currently.  Without sharing the same view model ala MulticastVM, you would need an independent state management service (like a Redux store) injected into each client's view model which subscribes to changed events from one view model, and raises state changed events for other view models to subscribe to and update their own states.

**Comment by dsuryd** [comment]
I'm not clear, can you elaborate?
