### ISSUE TITLE
Notify client about the exception from IExceptionMiddleware

### ISSUE THREAD

**Issue by sushant-cyclotron** [dsuryd/dotNetify#160]
Can we use `HubCallerContext` parameter or is there any other way to notify client about the exception from `OnException` method?

**Comment by dsuryd** [comment]
The exception type and message will be sent back to the client, and by default will be shown in the console log.  This behavior can be overridden on the client by providing the `exceptionHandler` function in the options argument when calling `connect`.

The exception middleware can also change the exception by simply returning the desired exception.  This is illustrated in the documentation example.
