### ISSUE TITLE
Using social logins

### ISSUE THREAD

**Issue by OracPrime** [dsuryd/dotNetify#164]
Hi,

I'm, attempting to set up a dotnetify project using data from Strava, which uses OAuth2.  I think I can see a way of doing this in a dotnetify context, but it's looking a bit messy.  And things in dotnetify are normally nice and clean, so I was wondering if there is a clean example of how to do this anywhere?

Keep up the good work - really liking the way dotnetify is progressing!

**Comment by dsuryd** [comment]
I would just use the standard ASP.NET authentication to resolve the user principal context before displaying dotNetify views.

**Comment by OracPrime** [comment]
So setup a standard mvc page with welcome and login and once authenticated go to the SPA? Makes sense. Let's hope the different routing setups don't fight!

**Comment by dsuryd** [comment]
Closing this as the question has been answered.
