### ISSUE TITLE
PushUpdates/Changed inside a class

### ISSUE THREAD

**Issue by DG4ever** [dsuryd/dotNetify#17]
I have a problem with updating the view when a property is changed inside a class.

I got a class for translating a text:

_public string TableName { get; set; }_
_public string Content { get; set; }_
_public string TranslatedText { get; set; }_

_public DictionaryText(string tableName, string content)_
_{_
	_TableName = tableName;_
	_Content = content;_
	_TranslatedText = content;_
	_MainWindowVM.OnLanguageChanged += LanguageChanged;_
_}_
_private void LanguageChanged(object source, LanguageEventArgs e)_
_{_
	_string language = e.GetLanguage();_
	_TranslatedText = CommonTableReader.GetMessage(Content, TableName, language);_
_}_

I am using this class as a property in a ViewModel for my Page:

_public class MainPageVM : PageVM_
_{_
         _public DictionaryText PageName { get; set; }_ 
	 _public MainPageVM()_
         _{_
                 _PageName = new DictionaryText("messages", "Descr_MainPage");_
         _}_
_}_

This is the HTML Code:

`<h3 data-bind="text: PageName.TranslatedText"></h3>`

The problem is that the TranslatedText is not updated when the event occurs. When I manually call `Changed(()=>PageName)` in the MainPageVM it is updated correctly. Is there a way to call Changed inside the DictionaryText class?

**Comment by dsuryd** [comment]
Hi, the standard MVVM approach on propagating changes is for the subclass to implement `System.ComponentModel.INotifyPropertyChanged` interface and propagate to the higher level any change made to its properties.

In dotNetify, there's a helper base class called `Observable` that provide basic implementation of that interface.  So in your case:

```
class DictionaryText(...) : Observable
{
   ...
    public string TranslatedText { get { return Get<string>(); } set { Set(value); } }
...

public MainPageVM() 
{
   PageName = DictionaryText(...)
   PageName.PropertyChanged += (sender, e ) => Changed(()=>PageName);
}
```

**Comment by DG4ever** [comment]
Thanks a lot.
I am now using reflection to automatically add Changed() to the PropertyChanged Event of all DictionaryText propertys. This works great. But I have some further questions:

1. Is there a way that only the TranslatedText Property is sent to the client and not the whole DictionaryText class?

2. What does PushUpdates() do and when should I use it instead of Changed()?

**Comment by dsuryd** [comment]
1. I suggest refactor to the following:

`<h3 data-bind="text: LocalizedPageName"></h3>`

```
public class MainPageVM : BaseVM 
{
   private DictionaryText _dictionaryText;

   public string LocalizedPageName{ get { return Get<string>(); } set { Set(value); } }

   public MainPageVM()
   {
       _dictionaryText = new DictionaryText(...);
       _dictionaryText.PropertyChanged += (sender, e ) => 
       {
           if ( e.PropertyName == nameof(DictionaryText.TranslatedText) )
               LocalizedPageName = _dictionaryText.TranslatedText;
       };    
   }
```

2.  Changed() only marks a property as "changed", nothing more.  In most scenarios, changed properties are only updated to the client as part of the action-reaction cycle, i,e. client initiates an action that sends updates to the server, the server then responds back by sending all the "changed" properties.   The PushUpdates() is used for certain scenario where the server wants to push updates to the client, without waiting for the client to initiate any action.  This was documented in the Real-Time Examples / Live Chart.

**Comment by DG4ever** [comment]
Thank you for clarifying and for your great support.

I got one last question to the Binding part. In your exapmle you used a simple standard <select> Element. Unfortionatly it is quite ugly. I tried the bootstrap-select picker but I can't get the Binding working between the c# ViewModel an the View. However it is working fine when binding to the code behind similar to this example: http://jsfiddle.net/bkzb272j/1/

I am sure I that I am doing something wrong but I can't figure it out. Could you provide an example using the bootstrap-select picker with a c# ViewModel?

**Comment by dsuryd** [comment]
A little bit tricky since the bootstrap-select passes JSON back, but here it is: 
https://gist.github.com/dsuryd/51e6bcf1d804fc7638f3ddc9bf961aa3

**Comment by dsuryd** [comment]
On commands inside a list, I have a couple of examples, one is in Basic Examples/Simple List (remove icon), and the other one is in dotnetify-app-template's MenuVM (Add buttons on list of menu items).

**Comment by DG4ever** [comment]
I looked at the examples and even in the dotnetify-app-template.
I really don't know what I am doing wrong. I tried with and without vmItemKey.

This is my HTML code:
```
<div class="col-xs-1 text-left p100" data-bind="foreach: SButtonL, vmItemKey: 'ID'">
        <div class="row-xs-1 text-center p15"><button data-bind="text: Text, vmCommand: ClickCommand" type="button" class="btn btn-default btn-block p100"></button></div>
</div>
```
This is my VM:

```
public class MainPageVM : BaseVM
{
	public List<SButton> SButtonL { get; set; }

	public MainPageVM()
	{
		SButtonL = new List<SButton>();
		for (int id = 1; id < 5; id++)
			SButtonL.Add(new SButton { ID = id, ClickCommand = new Command(() => OnClick(id)),, Text = id.ToString()});
	}

	private void OnClick(int id)
	{
		throw new NotImplementedException();
	}
}
```

And this is my Button:
```
public class SButton
	{
		public string Text { get; set; }
		public int ID { get; set; }
		public bool Enabled { get; set; }
		public bool Pick { get; set; }
		public bool Select { get; set; }
		public bool HomePos { get; set; }
		public bool WorkPos { get; set; }
		public bool InputLineVisible { get; set; }

		public ICommand ClickCommand { get; set; }
	}
```

**Comment by dsuryd** [comment]
You're missing this method in the VM class:

`public SButton SButtonL_get(string key) => SButtonL.FirstOrDefault(i => i.ID.ToString() == key);`

This is one way how dotNetify can resolve the path coming from client like 'SButtonL.$1.ClickCommand" into an actual object in the VM instance.  This was documented in Simple List  example side notes 'Update'.

The other way is to override `OnUnresolvedUpdate `base method, which will pass that raw path for you to parse yourself.
