### ISSUE TITLE
How to manually call PushUpdates from outside the BaseVM class

### ISSUE THREAD

**Issue by cuongdn** [dsuryd/dotNetify#180]
Hello,
Is there any way to call PushUpdates outside BaseVM like below tutorial (using Hub)?

https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-call-client-methods-and-manage-groups-from-outside-the-hub-class

**Comment by dsuryd** [comment]
If you're referring to server broadcast, look at [MulticastVM](http://www.dotnetify.net/core/api/multicast).

**Comment by cuongdn** [comment]
I mean how can I get instance of view model so that i can call vm.PushUpdates(). Is there any method similar to GlobalHost.ConnectionManager.GetHubContext<StockTickerHub>() to get view model instance?

**Comment by dsuryd** [comment]
There is no API to access a particular active view model.  If you need to call `PushUpdates` from outside the view model, consider using the Observer pattern.
