### ISSUE TITLE
PushUpdates is there a limitation (Does it work with arrays)?

### ISSUE THREAD

**Issue by undecided2013** [dsuryd/dotNetify#183]
I copied the simple hello world example and I am attempting to return an array of values back
  public class TestStrm : BaseVM
    {
// This is the property that I want to stream to client
public DataElement[] dataElements => GetBufferArray();
        private DataElement[] GetBufferArray()
        {
            return _buffer.ToArray();
        }

            _timer = new Timer(state =>
            {
                Changed(nameof(dataElements ));
                PushUpdates();
            }, null, 0, 1000);

I can see the array being full with data but nothing arrives at the client. I do break in the browser debugger and it stops at the population of the  dataElements  variable but length is zero.
Does this work with arrays?

p.s. If I replace
  return _buffer.ToArray();
with 
 return new DataElement[100] ;

I do get back the empty array.

p.p.s. I see the timer updating the page.

**Comment by dsuryd** [comment]
It works with array, as can be seen in the [live chart example](http://www.dotnetify.net/core/examples/livechart).  If there's problem, likely cause is the array item type isn't JSON serializable.

**Comment by undecided2013** [comment]
You are correct sir. Switching the array to string allowed it to work. The bizarre thing is that I am using Newtonsoft to serialize and deserialize the data that was going into that array so I do not understand why if newtonsoft can do it in my code, the same json would fail to make it to the client. I did see that you are also using Newtonsoft for the json serialization to the client. Do you have any idea why that would be the case? Thx

**Comment by dsuryd** [comment]
Do you see any exception in your VS debug output?  Could be the difference in the serialization settings, which you can control (see #105).
