### ISSUE TITLE
How to handle routing using another components for links?

### ISSUE THREAD

**Issue by lrhmx** [dsuryd/dotNetify#185]
I'm using Vuetify and I like to use the v-list componente for displaying the main menu with links to routes.

How I can handle the link without using <a> and v-vmRoute?

**Comment by dsuryd** [comment]
See this `v-vmRoute` directive implementation here: https://github.com/dsuryd/dotNetify/blob/master/DevApp/src/dotnetify/vue/directives.js

You can create your own directive that calls `vue.vm.$handleRoute` when the component is clicked.

**Comment by desarrollo03TR** [comment]
Thanks, at the end, the event passed to 'handleRoute' function requires a pathname property. The solution was to send an object with the right properties:

    Vue.directive('vmVMRoute', {
        bind: function (el, binding, vnode) {
            const vue = vnode.context;
            const route = binding.value;
            const ref = route && vue.vm ? vue.vm.$route(route) : '';
            el.addEventListener('click', function (e) {
                e.preventDefault();
                vue.vm.$handleRoute({
                    currentTarget: {
                        pathname: ref
                    },
                    event: e,
                    preventDefault: function () {
                         this.event.preventDefault();
                    }
                });
            });
        }
    });
