### ISSUE TITLE
Dependency Injection Support

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#187]
Want to make the constructor for my VM implementation DI-friendly. I need to include some other objects (interfaces) available in the constructor to make my VM unit testable. Do you have any guidance on how to do this?

**Comment by dsuryd** [comment]
DI is supported: http://dotnetify.net/core/api/di

**Comment by mojo-man** [comment]
Trying to setup my factory method - what am I doing wrong?
`			app.UseDotNetify(config => {
				config.SetFactoryMethod((typeof(IMessageReceiver), null) =>
					{
						return MessagingManager.GetMessageReceiver();
					});
			});
`

**Comment by dsuryd** [comment]
The factory method is for instantiating dotNetify view models only, and it's probably rare that anybody would need to override it.   Favor setting up a proper DI pipeline over this.

**Comment by mojo-man** [comment]
Got it - Thanks
