### ISSUE TITLE
Changed notification

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#189]
I have a change that happens several layers down inside of an object hierarchy. When I call the Changed() method, do I need to call Changed() on all levels of the hierarchy above it? If so - which order? Inside->Out or the other way?

**Comment by dsuryd** [comment]
The `BaseVM.Changed` method isn't intended for nested objects.  You should implement your own changed notification to let the top view model know to call `Changed` for the affected property.
