### ISSUE TITLE
How to authorize View Model Controls

### ISSUE THREAD

**Issue by SherifRefaat** [dsuryd/dotNetify#191]
In the following [Sample Page](https://dotnetify.net/core/examples/controltypes) the View Model contains the following control the gets called from the client:
` public Action<bool> ButtonClicked => _ => ClickCount++;`

My question is how to authorize this control.

For example, in MVC controller you can add the `Authorize` or `Authorize(...)` attribute on the controller. Additionally, you could have an action called 
`public IActionResult DeleteUser(int id) {...}`  
that do a functionality that require higher role or policy than initially declared on the controller. So you would add the `Authorize` attribute on the action and that would work.
```
[Authorize(higherRole)]
public IActionResult DeleteUser(int id) {...}
``` 

Is there is some mechanism here to do so?
Or how do you envision doing this?
Or I have to manually check for policy or roles inside the above control (or action in the previous example)?

Thanks.

**Comment by dsuryd** [comment]
There's no method-level auth attribute, and it won't feel right to have it with the MVVM paradigm.  Those methods are not equivalent to stateless MVC controls, they're closely integrated with the view.   

It's better not to mix responsibility for different roles in one view model.  Seek to separate them to different view models.  They can share the same code through composition or inheritance.
