### ISSUE TITLE
reconnect to new hubServerUrl 

### ISSUE THREAD

**Issue by behnam-basketasia** [dsuryd/dotNetify#192]
In my project, I set hubServerUrl in the main.js, but i want to ping many server and then connect to best one, i need to disconnect from previous hubServerUrl and then connect to new hubServerUrl. How can i handle this changing hubServerUrl? Is it possible to change it base on an event?
i try to use it for changing url but cant connect to new one:
```
dotnetify.hub.init()  
dotnetify.hubServerUrl = "http://www.domain.com";

```

**Comment by mason-chase** [comment]
This is very useful feature for us if we can have it, a server may go down or get overloaded, so client can determine a better or alternative server at any given time in multi-server environment.

This would eliminate the need for GLSB's such as Amazon Route 53's latency based dns, not to mention with DNS we may not quickly and seamlessly switch user to a new working server as DNS would take a while to update.

**Comment by dsuryd** [comment]
Try this:

Add the following to `main.js`, and then you only need to set `dotnetify.hubServerUrl` to switch server.
```jsx
import dotnetify from 'dotnetify';

Object.defineProperty(dotnetify, 'hubServerUrl', {
  get: () => dotnetify.hub.url,
  set: url => {
    dotnetify.hub.url = url;
    if (dotnetify._hub) {
      dotnetify._hub = null;
      dotnetify.startHub();
    }
  }
});
```

**Comment by behnam-basketasia** [comment]
I'm so grateful for your help
