### ISSUE TITLE
We’re trying to integrate the “Fuse React Theme” with https://dotnetify.net/

### ISSUE THREAD

**Issue by mliceagaglob** [dsuryd/dotNetify#193]
We're using a react template the company bought (http://fusetheme.com/admin-templates/react/) and followed their instructions, the template depends on "yarn" instead of npm, so we're having some issues trying to integrate dotnetify into it.

When we add the dotnetify to the packages json, and create the basic structure (using the instructions used in https://dotnetify.net/core/getstarted), and then modified the C:\PocReactCore\my-app\src\app\main\example\Example.js, the C:\PocReactCore\my-app\dotnetifytointegrate.csproj and the C:\PocReactCore\my-app\webpack.config.js an error shows up:
ERROR in ./src/app/App.js
      Module build failed (from ./node_modules/babel-loader/lib/index.js):
      Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

We then tried executing yarn again and it throws the following warnings:
yarn install v1.16.0pp>yarn
[1/4] Resolving packages...
warning Resolution field "react@16.8.5" is incompatible with requested version "react@^15.6.2"
warning Resolution field "react-dom@16.8.5" is incompatible with requested version "react-dom@^15.6.2"
success Already up-to-date.

I can't attach the sample project with the complete integration and steps described above because of copyright restrictions, but if you could provide me an email address I'd be happy to share it with you, it might be an edge case, or maybe it's me (the developer) being stupid :)

Looking forward to hear from you and Best Regards,

**Comment by dsuryd** [comment]
I assume that your "fusetheme" template already come with its own webpack build system and react dependencies included, therefore don't follow dotNetify's getstarted instructions.  Install dotNetify with yarn : `yarn add dotnetify`.

**Comment by mliceagaglob** [comment]
Hi Dicky, 
I tried what you said and it kind of worked for the react and babel conflicts, plus a couple of things I had to do. I also installed DotNetify.SignalR from nuget, and configured the "proxy" to "http://localhost:5000/" and now I'm getting the following errors in Chrome's console:

- Information: Normalizing '/dotnetify' to 'http://localhost:3000/dotnetify'.
- HttpClient.js:162 POST http://localhost:3000/dotnetify/negotiate 500 (Internal Server Error)

I tried wrapping the call to dotnetify using:
import { withRouter } from 'react-router-dom';
withRouter(dotnetify.react.connect('HelloWorld', this));

Information: Normalizing '/dotnetify' to 'http://localhost:3000/dotnetify'.
HttpClient.js:162 POST http://localhost:3000/dotnetify/negotiate 500 (Internal Server Error)

**Comment by dsuryd** [comment]
As your UI is served by a different server on port 3000, you'll need to tell dotNetify client where to find the hub server:   `dotnetify.hubServerUrl = 'http://localhost:5000'`.   Declare this once in your root js file, and make sure your hub server has CORS enabled.

**Comment by mliceagaglob** [comment]
Thank you very much! That really helped!
