### ISSUE TITLE
Issue with Customized with Json serializations configuration

### ISSUE THREAD

**Issue by mason-chase** [dsuryd/dotNetify#195]
Hi,

[UseJsonSerializerSettings](https://github.com/dsuryd/dotNetify/blob/b3e5fe7954011178bbe0a6c16bbb30ea046cf852/DotNetifyLib.Core/DotNetifyConfiguration.cs#L43) currently doesn't allow access to original `VMSerializer.SerializerSettings` value to avoid serializing `Action` and `ICommand` properties.

To [VMContractResolver](https://github.com/dsuryd/dotNetify/blob/b3e5fe7954011178bbe0a6c16bbb30ea046cf852/DotNetifyLib.Core/BaseVM/VMSerializer.cs#L34)  to work properly I have added additional methods to give us better direct access to instantiate Dotnetify's Json converter.

Regards
Mason

**Comment by mason-chase** [comment]
Apparently there are existing code in the project that doesn't meet the standard, should I make further changes on other areas to suppress the code standard error?

**Comment by dsuryd** [comment]
Looks good.  The failing standard check looks to be false positive, can be ignored.  
Could you add the unit test in [DotNetifyConfigurationTest.cs](https://github.com/dsuryd/dotNetify/blob/master/UnitTests/DotNetifyConfigurationTest.cs)?
