### ISSUE TITLE
jQuery was not found error every time I try to use Visual Studio + Webpack 

### ISSUE THREAD

**Issue by SonnyCampbell** [dsuryd/dotNetify#20]
When I try to follow the "[Hello World](http://dotnetify.net/react/from-scratch-vs)" example from Visual Studio/Webpack I get a jQuery was not found error.

![image](https://cloud.githubusercontent.com/assets/4961041/23833329/c4ab8494-073b-11e7-8e4e-4965198381fa.png)

I followed the steps exactly using both VS 2017 and VS Code, and got the same error both times.

I noticed when running Webpack that the list of bundled files didn't contain the jquery.js file that you showed in the image of your example.
![image](https://cloud.githubusercontent.com/assets/4961041/23833368/3b04880c-073c-11e7-86a5-e11808fa9f7c.png)
![image](https://cloud.githubusercontent.com/assets/4961041/23833370/3f86be7c-073c-11e7-9c0d-11d6e6933f65.png)

Do you have any idea if I've made a mistake, or if there is another step I need to do? I've tried to follow the steps you posted multiple times on 2 machines and got the same issue on both.

Thanks,
Sonny

**Comment by dsuryd** [comment]
So sorry, the HelloWorld.jsx part was incorrect.  This should fix the issue:
```
import React from 'react';
import $ from 'jquery';
window.jQuery = $;
var dotnetify = require('dotnetify');
```
Thank's for spotting this.  I'll update the docs.

**Comment by dsuryd** [comment]
Corrected the docs and added repository [dotnetify-react-demo-vs2017](https://github.com/dsuryd/dotnetify-react-demo-vs2017).

**Comment by SonnyCampbell** [comment]
Thank you so much for the quick reply, it's working perfectly now! Really appreciate the help.

**Comment by dsuryd** [comment]
Just an update - went back to using 'import' and this time use webpack's ProvidePlugin to set jQuery to global window variable.  Much cleaner this way.  Docs have been updated.

**Comment by LeeAtZoetik** [comment]
Getting the same problem using the Create-React-App HelloWorld sample

**Comment by dsuryd** [comment]
If you meant the one in github dotnetify-react-demo/HelloWorld, I just retested a fresh clone, but didn't see any issue.  How did you encounter the error?

**Comment by LeeAtZoetik** [comment]
I cleared out everything and then restarted from scratch following: http://dotnetify.net/react/create-react-app (I didn't even use Yarn this time ;-) )
From the debug console in Chrome I get the following:
Uncaught Error: jQuery was not found. Please ensure jQuery is referenced before the SignalR client JavaScript file.
    at jquery.signalR.js:46
    at Object../node_modules/signalr/jquery.signalR.js (jquery.signalR.js:986)
    at __webpack_require__ (bootstrap 7f1135573077c86e7812:669)
    at fn (bootstrap 7f1135573077c86e7812:87)
    at ./node_modules/dotnetify/dist/dotnetify-react.js.signalR (dotnetify-react.js:23)
    at Object../node_modules/dotnetify/dist/dotnetify-react.js (dotnetify-react.js:34)
    at __webpack_require__ (bootstrap 7f1135573077c86e7812:669)
    at fn (bootstrap 7f1135573077c86e7812:87)
    at Object../src/HelloWorld.jsx (App.js:23)
    at __webpack_require__ (
...

**Comment by dsuryd** [comment]
Thank you so much for pointing this out! Back to using this in HelloWorld.jsx for create-react-app:
```
import React from 'react';
import $ from 'jquery';
window.jQuery = $;
var dotnetify = require('dotnetify');
```

**Comment by LeeAtZoetik** [comment]
Yep - fixed it - thanks
