### ISSUE TITLE
JWT Token

### ISSUE THREAD

**Issue by msamara** [dsuryd/dotNetify#200]
Any idea hot to send JWT token upon connecting? currently getting 401 status code when negotiating with the initial connection, I had this before, JWT token needs to be sent with the request as in original SignalR:

connection = new HubConnectionBuilder()
        .withUrl(
          `${Vue.prototype.$http.defaults.baseURL}/question-hub`,
          jwtToken ? { accessTokenFactory: () => jwtToken } : null
        )
        .configureLogging(LogLevel.Information)
        .build()

**Comment by dsuryd** [comment]
DotNetify has a custom JWT handling; the token is passed inside websocket request instead the URL query string.  Consequently following SignalR documentation on token authentication won't work,  you need to follow [dotNetify documentation on the subject](https://www.dotnetify.net/core/api/security).
