### ISSUE TITLE
dotnetify.net is down

### ISSUE THREAD

**Issue by lilasquared** [dsuryd/dotNetify#206]
Not really an issue with the repo but if you aren't aware the https://dotnetify.net/ website is returning 503 for me.

**Comment by dsuryd** [comment]
Thanks; it's up now, the ISP provider did mention they're doing server migration.

**Comment by lilasquared** [comment]
seems to be still down for me but if they are fiddling with things then it must be that

**Comment by dsuryd** [comment]
There's an IP address change, it'll take time to complete the DNS propagation.  Here's a temporary address: dotnetify.net.198.gppnetwork.com
