### ISSUE TITLE
Issue on sending byte[] ?

### ISSUE THREAD

**Issue by roozbehid-ic** [dsuryd/dotNetify#209]
I am sending byte[] property back and forth and the data is not same....
Is this a known thing?
Should I do utf8 encoding or some other work arounds?

**Comment by dsuryd** [comment]
I've not worked with bytes.  The closest I've tried is sending images but always converted to base64.  Check SignalR documentation if they support it.

**Comment by roozbehid-ic** [comment]
Couldnt find more info on SignalR but for future visitors there is an issue if you use "byte[]", it is better to switch to "string" on your server and do Base64 encoding of bytes and on the client use "atob" and charCodeAt to extract bytes.
