### ISSUE TITLE
Download / Upload files 

### ISSUE THREAD

**Issue by Ajitweb** [dsuryd/dotNetify#21]
Hello Dicky,
Further to our discussion in another thread : 

As per your suggestion, to download a file, I am setting a VM property with the generated pdf file location. On the client side, listen to this property changed event, and then execute a window.open() to open the file on the browser.

Works fine, but in this approach there is a small security risk, as the full path of the location can be known - and hence it will be just a matter of time, when other users on the network will figure out my logic and starting "experimenting" with  urls on their browsers to download files generated from other users.

For generated files, maybe I can delete these generated pdf files on the server periodically (these generated pdfs can be stored in a 'temporary' directory), but then what about files which are part of a "document management system" which are stored on specific directories on the server. One way, I can think of is that the method will copy the desired files from the "documents" directory to the temporary directory which will then be served to the client and then similar to the generated pdfs, keep on deleting these files periodically.

Is there no way that I can have something like the response object of mvc, where the file is being "pushed" to the client browser. 

Appreciate your views on how to tackle this situation in dotnetify.

In Asp.net MVC, I used the response object to serve the files from such directories and the `<hiddenSegments>` in the web.config will make sure that the browser does not have direct access to that directory.

**Comment by dsuryd** [comment]
Hi Ajit, to mitigate the security risk, copy the requested pdf to the temporary directory (browsing disabled) with a random file name (System.IO.Path.GetRandomFileName) and pass that name to the VM.  You can set up a scheduler job to periodically clean up that directory.

About putting the pdf content into the HTTP response, check out [this article](http://www.c-sharpcorner.com/uploadfile/afenster/how-to-download-a-file-in-Asp-Net/).

**Comment by Ajitweb** [comment]
Thanks Dicky for your answer.
So, instead of setting up the scheduler, I thought of deleting the files straight away after being downloaded on to the client

So I created a server vm property that would be called by the client after the document is downloaded.

```
//open the report when pomast_send_filename_forclient is populated.
vm.$on(vm.pomast_send_filename_forclient, function () {
  var pdf = vm.pomast_send_filename_forclient();
       if (pdf) {
             window.open(pdf);
              vm.pomast_send_filename_delete("deleteme"); //delete the file from the server
       };
 });
```
and on the server

```
        public string pomast_send_filename_delete
        {
            get  { return Get<string>(); }
            set
            {
                //delete the file stored in pomast_send_filename_onserver
                if (File.Exists(pomast_send_filename_onserver))
                    File.Delete(pomast_send_filename_onserver);

                Set("abcd");
                Changed(() => pomast_send_filename_delete);
            }
        }

```
But the pomast_send_filename_delete property is never being called!.
On stepping through the code, I found that the $serverUpdate property is false.

I am setting many server properties in other parts of the code without any problems. ($serverUpdate is true)
But only in this instance, the serverUpdate is false. I cannot figure that one.
For the time being I am manually turng the serverUdpdate to true before setting the 'deleteme' value

```
          //open the report when pomast_send_filename_forclient is populated.
            vm.$on(vm.pomast_send_filename_forclient, function () {
                var pdf = vm.pomast_send_filename_forclient();
                var su = vm.$serverUpdate();
                if (pdf) {
                    window.open(pdf);
                    vm.$serverUpdate = true;
                    //For some reason $serverUpdate is false, hence the below value is never sent to the server
                    vm.pomast_send_filename_delete("deleteme"); //delete the file from the server
                    vm.$serverUpdate = su; //restore the original value
                };
            });
```

**Comment by dsuryd** [comment]
Hi Ajit, I'm going to answer the $serverUpdate issue first.  It's a safeguard feature to prevent feedback loop if the new data is triggering server update while still in binding process.  It will be set to false inside the $on scope.  In general, avoid doing synchronous server update on a function that is called on receiving new data from the server.  Do asynchronously instead, i.e. execute that update inside setTimeout.

**Comment by dsuryd** [comment]
I think you can still salvage the window.open method. Don't pass the URL to the pdf file, but pass the controller action URL instead, with pdf file as param, e.g. /getFile/<filename>,   Then in that controller, read the file, return its content in the action result, and then delete the file.

**Comment by Ajitweb** [comment]
Perfect!  :+1: 
I passed the controller / action / pdf filename   in the window.open() method and the file gets downloaded and then I delete it !
Perfect!
This also means that I don't have to tinker with $serverupdate property

As far as the download was concerned, there was no need to pass any further parameters to it.
But when I upload a file through the action method, then I need to identify myself . So please guide me with how to upload a file from outside dotnetify. The action method will need to access the instance of the VM.

Thanks once again Dicky for your help.

**Comment by dsuryd** [comment]
What's the upload workflow that you're thinking?

**Comment by Ajitweb** [comment]
Hi Dicky,

It is simple.
Every transaction has a list of documents attached to it.
Pls see the picture
![image](https://cloud.githubusercontent.com/assets/5118787/25052622/6b089ed8-215b-11e7-9149-cbbd22ae3f2a.png)

The first tab shows the list of transactions (in this case, a list of purchase orders)
When a specific purchase order is clicked, the second tab (with the transaction details) and the third tab (with the list of documents relevant to the transaction) is shown. 

It is in the third tab, that i want to give the upload button which uploads the documents to a specific location. You told me earlier that uploading of documents has to be done outside dotnetify. This is where I need your guidance of how exactly to do it. I mean not the uploading part (which can be achieved by many good jquery modules ) but after the upload to the mvc controller - how to inform the controller that upload is from a authenticated dotnetify vm and also pass to it the transaction id so that the controller knows where to place the documents)

Regards

**Comment by dsuryd** [comment]
Looks like your app is coming along nicely :)
Here's what you can do.  When you call the controller from the client, pass along `$.connection.hub.id`.
In the MVC controller:
```
var vmController = DotNetify.VMControllerFactory.Singleton.GetInstance(connectionId);
var data = new Dictionary<string, object>();
data.Add("<property name>", <property value>);
vmController.OnUpdateVM(connectionId, "<vm type name>", data);
```

**Comment by Ajitweb** [comment]
Thanks Dicky.

I pass the connectionid and the vmid through ajax

```
 $('#upload-file').click(function () {

                var formData = new FormData();
                var files = $("#my-file-selector").get(0).files;

                formData.append("file", files[0]);
                formData.append("connectionId", $.connection.hub.id);
                formData.append("vmId", vm.$vmId);

                $.ajax({
                    type: 'POST',
                    url: "/Home/Putfile",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                })
            })
```

The setting of a vm property works fine in the controller.
But how to get a value of a property of the vm in the controller.
I tried the onRequestVM but it is not working.

**Comment by dsuryd** [comment]
There's no API to read view model from the controller, as it is intended only to communicate with the view.  As far as I can understand, you just want your controller to tell the view model that an upload is complete; if there's read operation, can it be done from the view?

**Comment by Ajitweb** [comment]
There are some properties that I need to access from the vm, which decides the name of the document and where it has to be stored. 
I can always pass these information from the view to the controller - so no issues if there is no such API. 

Thanks once again Dicky.

I know that my ERP is nothing compared to the great ones out there so security is not much of an issue.
But is there any way that once it is in production environment, a developer can take hold of the 
$.connection.hub.id and play havoc with the vm ?

**Comment by dsuryd** [comment]
It requires user to be authenticated first to have access the controllers and the VMs; once authenticated, it is your responsibility to program in such a way that the user will only have access to the data he is authorized to.
