### ISSUE TITLE
Add Svelte support

### ISSUE THREAD

**Issue by DiverOfDark** [dsuryd/dotNetify#210]
It would be nice to have an frontend library for svelte (or some low-level library that anyone could import for not-so-popular-yet-frameworks)

**Comment by dsuryd** [comment]
Current version already supports generic use on frameworks other than listed.  For example, Angular isn't directly supported, but it can work nonetheless ([Demo code here](https://github.com/dsuryd/dotNetify/blob/a4746cccb2899615e6c7a213d58681d1240ab7f7/Demo/Angular/src/app/app.component.ts#L14-L17)).  It'd be great if you could write similar demo for Svelte.
