### ISSUE TITLE
Initial Routing setup using Hooks

### ISSUE THREAD

**Issue by RobertTheGrey** [dsuryd/dotNetify#211]
I don't think this is an issue - I'm almost certainly wiring things up incorrectly when using the recently added Hooks documentation. Things are working fine in other components, but the initial routing wiring is causing this error to be thrown: 
```
RouteLink requires 'vm' property. 
    in RouteLink (created by App)
    in App (created by Layout)
    in Layout
```
My experimental code looks like this:
```
import React, { useState } from 'react';
import { useConnect } from 'dotnetify';
import { RouteLink } from 'dotnetify/react';
import { auth, getAuthHeaders } from './auth';

const App = _ => {
  const { vm, state } = useConnect(
    'App',
    { authenticated: auth.hasAccessToken() },
    getAuthHeaders()
  );

// This is where I think I'm wiring things up incorrectly
  if (vm && !vm.onRouteEnter)
    vm.onRouteEnter = (path, template) => (template.Target = 'Content');

  return (
    <div>
      <nav className="navbar is-fixed-top">
         <div id="NavMenu" className="navbar-menu">
          <div className="navbar-start">
            <RouteLink
              vm={vm}
              route={state.NavMenu ? state.NavMenu[0].Route : null}
              className="navbar-item"
            >
              Home
            </RouteLink>
          </div>
         </div>
        </div>
      </nav>
      <div id="Content"></div>
    </div>
  );
};
```

If  I use a class-based component and wire it up in the constructor then this error obviously doesn't occur, so I think it's just how I'm using the Hooks based approach incorrectly. Is there other documentation or a sample I can look at to do things better?

Many thanks in advance!

**Comment by dsuryd** [comment]
The problem was that `vm` didn't have value on initial render, so you'll have to add a check there.  The [React SPA demo](https://github.com/dsuryd/dotNetify/tree/master/Demo/React/SPA) has been updated to show some Hook examples.

**Comment by RobertTheGrey** [comment]
Fantastic, many thanks @dsuryd
