### ISSUE TITLE
Building in Visual Studio for Mac.

### ISSUE THREAD

**Issue by daspuru** [dsuryd/dotNetify#22]
Hi, 

I am trying to build and run in Visual Studio for Mac, and I am able to build and run Webapplication.Core, however a blank screen responds on the browser.

Any clues?

Thanks.

**Comment by dsuryd** [comment]
It was caused by using backslash on URL path inside HomeController.cs.  Replace with slash, and it will run.

**Comment by daspuru** [comment]
Thanks. I changed the backslash in the paths and it compiled.  :) Greetings!
