### ISSUE TITLE
Add support for Microsoft.AspNetCore.SignalR.Protocols.MessagePack

### ISSUE THREAD

**Issue by MasterKolka** [dsuryd/dotNetify#221]
Hi,
It would be nice to add support for Microsoft.AspNetCore.SignalR.Protocols.MessagePack for better performance.
https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-3.0

**Comment by dsuryd** [comment]
Solved by providing access to `HubConnectionBuilder`  (see https://www.dotnetify.net/core/api/connection)

**Comment by MasterKolka** [comment]
Thanks!
It doesn't work with authentication..
