### ISSUE TITLE
Add typescript support for 3.5.0 version

### ISSUE THREAD

**Issue by ThomasMerant** [dsuryd/dotNetify#222]
Hi,

Can you add support for these version ?

I use useConnect and I have just write this : 
```typescript
import dotnetifyVM, { IConnectOptions } from "dotnetify";

declare module "dotnetify-3.5.0" {
    /* Waiting Typescript support :  */
    export function useConnect<T>(iVMId: String, initialState: T, iOptions?: IConnectOptions): { vm: dotnetifyVM, state: T };
}
```

**Comment by dsuryd** [comment]
It'd be great if you or anyone can help with this as I currently don't use Typescript.
Here's the location of the typed definition to update:
https://github.com/dsuryd/dotNetify/blob/master/DevApp/src/typings/dotnetify.d.ts

**Comment by ThomasMerant** [comment]
Pull request with only useConnect support : [https://github.com/dsuryd/dotNetify/pull/223](url)

**Comment by dsuryd** [comment]
Merged.  Thank's!
