### ISSUE TITLE
IPrincipalAccessor returns same user after another login

### ISSUE THREAD

**Issue by marcotana** [dsuryd/dotNetify#224]
The current user doesn't seem to get updated when the user logs out and another user logs in without refreshing the browser.  If I refresh the browser with the new user logged in, then I see the new user's identity. Do I need to do something different to make sure that the user I get from IPrinicpalAccessor (injected in a VM) always returns the current user?

**Comment by dsuryd** [comment]
Anything that you're doing differently to the example provided by dotnetify-react-template? 

If you run that project, you can see the user name below always displays the correct logged in user.

![image](https://user-images.githubusercontent.com/14990482/69469925-5ef2d380-0d48-11ea-827a-ef80598aaf62.png)

![image](https://user-images.githubusercontent.com/14990482/69469980-96fa1680-0d48-11ea-9bc9-a7db50f9198d.png)

**Comment by marcotana** [comment]
I'll investigate further.  I am using ASPNETCORE 3 so there may be some middleware issues that I'm having.  Anyway, one thing that I did notice that Dotnetify middlewares do not get invoked when the VM is connected using the "Scope" element.  I'm not sure if you want me to create a new issue on this.  If so, just let me know.  I'll close this depending on your answer.

**Comment by dsuryd** [comment]
Let's create a separate issue for the Scope, and please include steps to reproduce.
