### ISSUE TITLE
Hello World example "return window.vmStates.HelloWorldVM;" not working correctly.

### ISSUE THREAD

**Issue by SonnyCampbell** [dsuryd/dotNetify#23]
I've been playing around with the Hello World code example, however I consistently get an error when the getInitialState() method of the HelloWorld.jsx class calls "return window.vmStates.HelloWorldVM;".

The error I get is (I renamed HelloWorldVM to FormTestVM, everything else is identical):

> Uncaught TypeError: Cannot read property 'FormTestVM' of undefined
>     at Object.getInitialState (eval at <anonymous> (bundle.js:1075), <anonymous>:34:31)
>     at new eval (eval at <anonymous> (bundle.js:2155), <anonymous>:653:54)
>     at eval (eval at <anonymous> (bundle.js:1411), <anonymous>:297:18)
>     at measureLifeCyclePerf (eval at <anonymous> (bundle.js:1411), <anonymous>:77:12)
>     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (eval at <anonymous> (bundle.js:1411), <anonymous>:296:16)
>     at ReactCompositeComponentWrapper._constructComponent (eval at <anonymous> (bundle.js:1411), <anonymous>:282:21)
>     at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (bundle.js:1411), <anonymous>:190:21)
>     at Object.mountComponent (eval at <anonymous> (bundle.js:295), <anonymous>:46:35)
>     at ReactDOMComponent.mountChildren (eval at <anonymous> (bundle.js:1723), <anonymous>:238:44)
>     at ReactDOMComponent._createInitialChildren (eval at <anonymous> (bundle.js:1435), <anonymous>:699:32)

and it is always thrown at this line:

>  return window.vmStates.FormTestVM;

I changed this to:

> return this.vm;

and it seems to work correctly. Is there something I have done incorrectly, or is this a bug?

**Comment by dsuryd** [comment]
You probably haven't renamed the routing template registration in IndexVM to FormTestVM.  Getting initial state from the server is an optional routing feature explained [here](http://www.dotnetify.net/react/Routing).   The geInitialState should just return empty state (or client-only state) if not using this feature, so your returning 'this.vm' isn't correct.
