### ISSUE TITLE
Potential bug with UseJsonSerializerSettings config option and CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by samartzidis** [dsuryd/dotNetify#230]
If I globally configure the dotNetify serializer to use the CamelCasePropertyNamesContractResolver and a viewmodel contains "state changer" actions, I get a JS-side error such as this:

`Self referencing loop detected for property 'module' with type 'System.Reflection.RuntimeModule'. Path 'dummyAction.method.module.assembly.entryPoint'.`

and at the C# backend:

```
Fail: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'target' with type 'ServiceTierDashboard.ViewModels.DummyVm'. Path 'dummyAction'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
```

and then the C# backend viewmodel JS binding completely fails.

Example:
```
public class DummyVm : BaseVM
    {
        public string DummyName { get; set; } = "Hello World";
        
        public Action<string> DummyAction => v => { DummyName = v; }; // <- causes trouble
    }
```

This does not happen if CamelCasePropertyNamesContractResolver is not used or if I explicitly set the [JsonIgnore] attribute on the DummyAction property:

```
[JsonIgnore]
public Action<string> DummyAction => v => { DummyName = v; };
```

**Comment by dsuryd** [comment]
Overriding the contract resolver is tricky because dotNetify needs its own resolver to prevent serialization of action properties just as you discovered (reference: issue #105).  If all you need is camel case naming, have this instead:
```csharp
config.UseJsonSerializerSettings(x => x.ContractResolver = new VMContractResolver() { NamingStrategy = new CamelCaseNamingStrategy() });
```

**Comment by samartzidis** [comment]
That did the trick. Thank you.
