### ISSUE TITLE
ASP.NET WebApi (but .net Framework) and Create React App

### ISSUE THREAD

**Issue by marshmit** [dsuryd/dotNetify#234]
Hi,

I need to create a WebApp that relies on a large amount of libraries written for the .net Framework (and converting to .net core is not trivial). I really like dotNetify as it fits well with the structure of the project (there exist many WPF applications based on these libraries).
React is the desired View framework and CRA the way that we would go for that. I followed the example how to make dotNetify ASP.Net Core WebApis work, but I am a bit lost how to do it with APS.Net Framework WebApis.

I looked at the HelloWorld ASP.Net (Framework) MVC example but it's not a great fit for the CRA (I think).

Does somebody have a simple example for CRA and ASP.Net Framework WebApi? Or some pointers what the right approach is. Sorry, my knowledge of .net webservices is fairly limited, I have a web developer who is great with react but the knowledge of .net is fairly limited ;), so we appreciate any help.

Thank you.

**Comment by dsuryd** [comment]
The Web API mode is only available with .NET Core, and I currently don't have plan to port it to .NET Framework.  Is using SignalR not viable?  

If you or anyone is interested to contribute by porting it to the .NET Framework build (DotNetify.SignalR.Owin), [the code is here.](https://github.com/dsuryd/dotNetify/blob/master/DotNetifyLib.SignalR/DotNetifyWebApi.cs)
