### ISSUE TITLE
Compression (dot net core)

### ISSUE THREAD

**Issue by SherifRefaat** [dsuryd/dotNetify#236]
Hi, I am using your project for two years now and I have no problem whatsoever.
But right now I need to utilize compression in order to reduce the payload size. Can you help me with that?

Thanks.

**Comment by SherifRefaat** [comment]
Also, is there a property attribute that can ignore sending some kind of properties from my model?

**Comment by dsuryd** [comment]
Consider using [MessagePack protocol](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-3.1) to reduce SignalR message size.  Also, see issue #221.

Use [Ignore] to exclude a property from being sent to client.

**Comment by SherifRefaat** [comment]
Thanks.
