### ISSUE TITLE
Found a minor bug in React useConnect state using Lists.

### ISSUE THREAD

**Issue by potetball** [dsuryd/dotNetify#237]
When updating/modifying lists using useConnect, it overwrites state completely.
Workaround that i used: modify dotnetify-react useEffect function to combine state before setState.
from
vmData.current = newState;
to
vmData.current = Object.assign({},vmData.current,newState);

great work by the way, 
cheers

**Comment by dsuryd** [comment]
Thank you! Would you like to submit a PR?

**Comment by dsuryd** [comment]
Fixed in v3.7.
