### ISSUE TITLE
Problem with react-intl?

### ISSUE THREAD

**Issue by giuz78** [dsuryd/dotNetify#238]
Hi ,I’m trying to localize my DotNetify application using react-intl but I have a problem.
I have the same issue with DotNetify React template, I don’t understand if it’s a my trouble or something wrong with your library.
I added react-intl to package.json. I have changed ./app.js in :

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './routes.js';
import 'flexboxgrid/css/flexboxgrid.css';
import './styles/app.css';
import { IntlProvider } from 'react-intl';
import messages_en from "./translations/en.json";
import messages_it from "./translations/it.json";

const messages = {
    'en': messages_en,
    'it': messages_it
};

const language = navigator.language.split(/[-_]/)[0];


ReactDOM.render(
    <IntlProvider locale={language} messages={messages[language]}>
        <App id="App" />
    </IntlProvider>,
    document.getElementById('App'));
```

Then I tried to use the react-intl `<FormattedMessage> `component to translate text in my components.
If I put a `<FormattedMessage id=“test_message” /> ` (and relative `import { FormattedMessage } from 'react-intl';` ) in Header.js or Sidebar.js or Login.js I have my text translated as expected.
But If I put it in one view created by `this.vm.onRouteEnter = (path, template) => (template.Target = 'Content');`  like Dashboard.js or FormPage.js I have this error:

**[Error] Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.**
	

Thanks

**Comment by dsuryd** [comment]
The views are dynamically mounted, so they're not getting the context from <IntlProvider>.  You will need to wrap it on each view.

**Comment by giuz78** [comment]
Thanks. Ok it's clear, but how can I pass props to these views? Like the language selected by the user in another view, or other data need to render these views?

**Comment by dsuryd** [comment]
To pass props between views, use an intermediary data cache: have the prop value set in `onRouteEnter`, then have the newly routed view get it to initialize itself. This intermediary can be as simple as a global window variable, or a singleton, to something sophisticated like a Redux store.

**Comment by giuz78** [comment]
As you suggested I solved simply using a singleton.Now all views are localized and working.
Thanks for your support and your super work with dotNetify , it help me a lot to move winforms applications to web applications.Very good job :-) Thanks
