### ISSUE TITLE
typescript typings missing dotnetifyVM.$routeTo

### ISSUE THREAD

**Issue by Spongman** [dsuryd/dotNetify#240]
is this deprecated?

**Comment by dsuryd** [comment]
It's not; the typed definition is not complete.

**Comment by Spongman** [comment]
what about `IConnectionOptions`? https://dotnetify.net/core/api/routing#setting-up-route-links has this:
```typescript
const onRouteEnter = (path, template) => template.Target = "Content"; 
this.vm = dotnetify.react.connect("Index", this, { onRouteEnter });
```

but `IConnectOptions` doesn't have an `onRouteEnter`.

it's not entirely clear to me that the above code would work if it did...

**Comment by dsuryd** [comment]
Next version will have better Typescript support.  Until then, see the code in this branch for up-to-date typings: https://github.com/dsuryd/dotNetify/blob/Typescript/DevApp/src/dotnetify/_typings/index.ts

**Comment by Spongman** [comment]
i think probably those docs should be changed to use the `this.vm.onRouteEnter = ...` variant.

**Comment by dsuryd** [comment]
Updated typings in v4.  There are breaking changes from renamed types.
