### ISSUE TITLE
MulticastVM  per (vmInstanceId / GroupName)  

### ISSUE THREAD

**Issue by treg** [dsuryd/dotNetify#248]
I would have expected VMFactory.GetMulticastInstance  to return/create a MulticastVM per  vmInstanceId, just like BaseVM

However the key in GetMulticastInstance is only looking for vmType.FullName not vmType.FullName + '$' + vmInstanceId, like BaseVM

Is this behavior intended or is it a bug?

Also:

I have set MulticastVM.GroupName => vmInstanceId
Still returns the MulticastVM instance not a MulticastVM.GroupName instance

**Comment by dsuryd** [comment]
It seems to be an oversight; will investigate further when I have the chance.  What use case do you have for this?

**Comment by treg** [comment]
The use case is multiple simultaneous editors of a single instance of an
online form.

Where the vmInstance is the form instance id.

**Comment by dsuryd** [comment]
Fix is published in the latest.
