### ISSUE TITLE
Update JWT token

### ISSUE THREAD

**Issue by Sigve84** [dsuryd/dotNetify#251]
I am using JWT auth. The JWT has a TTL of 5 mins, so I need to update the JWT token at regular intervals. At the moment I am setting this in the header part of dotnetify.react.connect.  I am fetching a new JWT from the auth provder at regular intervals before it will expire, but how do I update the header to use for authorization from react?

this.vm = dotnetify.react.connect("vm", this, {
      headers: Auth.getAuthHeader(),
    });

**Comment by dsuryd** [comment]
Try this: `vm.dispatch({$headers: "<new token>"})`

**Comment by Sigve84** [comment]
Tried it, and it do not seem to work. principal = ValidateBearerToken(ParseHeaders<HeaderData>(hubContext.Headers), out validatedToken); still validates the old JWT token

**Comment by dsuryd** [comment]
There was a bug in the extract headers middleware which is now fixed in the repo.  This will be how a client can update the token in the headers:
```jsx
this.vm.$dispatch({ $headers: { Authorization: 'Bearer ' + jwt.access_token }})
```
