### ISSUE TITLE
Using SQL Backplane

### ISSUE THREAD

**Issue by cakriwut** [dsuryd/dotNetify#253]
I am trying to use SQL Backplane with Dotnetify.

I use this in my OWIN startup class

GlobalHost.DependencyResolver.UseSqlServer("");
app.MapSignalR();
app.UseDotNetify(option => option.RegisterAssembly(Assembly.GetExecutingAssembly()));

However, the hub does not work. Is there any guidance to use SQL Backplane with dotnetify?

**Comment by dsuryd** [comment]
I have no experience with backplanes and the topic is out of scope of this library.  Also, Microsoft is not recommending SQL Server backplane anymore: https://github.com/dotnet/aspnetcore/issues/5277
