### ISSUE TITLE
Debug Build

### ISSUE THREAD

**Issue by Elijah23Johnson** [dsuryd/dotNetify#256]
![image](https://user-images.githubusercontent.com/31963164/87234959-3d079900-c38b-11ea-9123-0dc4c4e38383.png)

This could be annoying.

**Comment by dsuryd** [comment]
I'm not clear what you're asking here.  The published DLL has to be a release build.

**Comment by Elijah23Johnson** [comment]
This is not standard behavior using a nuget package. The build
variable should align with devs build process.

**Comment by dsuryd** [comment]
OK, so this is basically the same as PR #254.

**Comment by Elijah23Johnson** [comment]
Yes Exactly. You can close this one in favor of PR #254.

**Comment by dsuryd** [comment]
Closed in favor of PR #254.
