### ISSUE TITLE
page displayed with UnauthorizedAccessException

### ISSUE THREAD

**Issue by roozbehid-ic** [dsuryd/dotNetify#258]
I have a page with [Authorize] attribute.
I am trying to figure out how to create a new custom authorization attribute 
but anyway, I only get this 

     UnauthorizedAccessException: Attempted to perform an unauthorized operation

in browser console and page still shows up.
is this normal behaviour?

**Comment by dsuryd** [comment]
Yes, that's expected if client is unauthorized.  You should add an exception handler on connect to provide your redirect.  See https://dotnetify.net/core/api/security.
