### ISSUE TITLE
Compability with ASP.NET?

### ISSUE THREAD

**Issue by ehellman** [dsuryd/dotNetify#26]
Would this solution be possible with ASP.NET as well? We're using a CMS that hasn't upgraded to .NET Core yet and won't do that in the foreseeable future. We're looking at implementing something similar to this there so that we can use React properly.

What things in .NET Core enabled you to use these things and if you were to implement this for ASP.NET are there any general tips on how to get this working?

**Comment by dsuryd** [comment]
This library supports older ASP.NET; in fact all live demo on the website is still running on v4.5.  For the back-end, use nuget package DotNetify (v.1.1.2) instead.
