### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by dbruning** [dsuryd/dotNetify#261]
This library looks awesome and I would like to use it for an upcoming project. My only concern is lack of commits over the last 2 months, so I would like to ask: is that because it’s complete, or because it’s abandoned?

I would be happy to support financially, just looking for an indication of the likely technical support for this project over (say) a 5-year timeframe.

**Comment by dsuryd** [comment]
Thank you for your interest! This project is still actively maintained.  It is pretty stable at the moment, and has met my goals for the year in terms of feature set.  I'm looking forward for users of this project to help drive future backlogs.

**Comment by dbruning** [comment]
Great, thanks for that info. I look forward to trying it out for my project.

**Comment by timeshift92** [comment]
hello, this project is not active since 1 year, project is maintained?
