### ISSUE TITLE
Xamarin Integration?

### ISSUE THREAD

**Issue by Warr1611** [dsuryd/dotNetify#27]
Are there any plans to have DotNetify support Xamarin? It seems like this would be a great fit, re-using Xamarin View Models in my Web Application. I've attempted installing this in a Portable Class Library (4.5, Profile=7) but received error:

"Could not install package 'Microsoft.Owin.Host.SystemWeb 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by dsuryd** [comment]
Xamarin is not in my radar at the moment.  You could try making your PCL target to .net standard and use the nuget package dotnetify.core, and on asp.net project use dotnetify.signalr.  I'm no expert but this thread might help: https://github.com/aspnet/Home/issues/1356
