### ISSUE TITLE
Question: onDisconnect infinite loop

### ISSUE THREAD

**Issue by ensemblebd** [dsuryd/dotNetify#272]
Am using version 4.1.1 and websocket signalR setup for .net core 3.1

For some reason I am getting an infite loop of "Error: Invocation canceled due to connection being closed"
Server side reports "[dotNetify] connId=xxxxx type=OnDisconnected"

It's occurring for every single request on a VM connected route. I can see it displayed, and everything is there. But it's constantly disconnected non stop ever 1 second and trying to reload itself. 

What's weird is the same code worked fine on different computer. 
Which leads me to believe it's possibly an npm package issue? Even though I'm using specific versions, and same node/npm version, perhaps a library (signalr??) is differing slightly?

Any ideas or pointers by chance?

**Comment by dsuryd** [comment]
You may have a signalR .net core client trying to connect with server running signalR .net framework.  There should be some console errors indicating protocol mismatch if that's the case.

**Comment by ensemblebd** [comment]
You were spot on. Unbelievable!!!!! I spent 6 hours trying to dig down through source code to no avail.
And here it is, sitting in a dependency project and not even being utilized, but it tanked the entire system. Was actually .net core variant, Microsoft.AspNetCore.SignalR.  Removal of that project (and thereby signalr reference) solved.
Thank you!!!
