### ISSUE TITLE
Getting active route info

### ISSUE THREAD

**Issue by behnam-basketasia** [dsuryd/dotNetify#281]
How can i get active route info in my `AppLayout Vm`, my `AppLayout vm` is place that i write all of my routingTemplate info. is there any way to find out active route info?
for example i wanna know if logout route that is a GET method is activated, before that `AppLayout` vm is called with related constructor, at this step, i want to get current Url, that in my example is /logout and set some strategy for it.

**Comment by dsuryd** [comment]
The `OnActivated` event from the `IRoutable` interface will get you the active route info.

**Comment by dsuryd** [comment]
Did I answer your question?  Please close this issue if so.
