### ISSUE TITLE
Wrong serialization on model updates

### ISSUE THREAD

**Issue by Paulskit** [dsuryd/dotNetify#295]
Hello @dsuryd!
Thank you for the library, it saves me a lot of time. 
Recently I noticed a strange behavior on the serialization.

I have a custom contract resolver:
```csharp
internal class CamelCaseContractResolver : VMContractResolver
    {
        public CamelCaseContractResolver()
        {
            NamingStrategy = new CamelCaseNamingStrategy();
        }
    }
```

It's registered in `Startup.cs`
```csharp
            app.UseDotNetify(o =>
            {
                o.UseJsonSerializerSettings(j =>
                {
                    j.ContractResolver = new CamelCaseContractResolver();
                });
            });
```

Then there is a model (simplified for sake of readability)
```csharp
public class ServicesVM : BaseVM
    {
        private readonly ILoader _loader;

        public ServicesVM(ILoader loader)
        {
            _loader= loader;
        }

        public IEnumerable<ServiceDto> Services
        {
            get => Get<IEnumerable<ServiceDto>>();
            set => Set(value);
        }        
        
        public override async Task OnCreatedAsync()
        {
            Services = await _loader.LoadAsync();
        }

        public async Task Update()
        {
            Services = await _loader.LoadAsync();
        }
    }
```

When the model is created and data is loaded in `OnCreatedAsync` I get nice camelCased properties in the response.
However, after `Update()` it seems to return PascalCased properties instead.

![image](https://user-images.githubusercontent.com/9947675/120442976-df0ee600-c38e-11eb-81c3-ef8c461336d4.png)

Can you please take a look? 
Thank you. Appreciate your effort.

**Comment by dsuryd** [comment]
I was able to reproduce the issue with that custom resolver, but no issue when using the built-in Newtonsoft resolver:

```csharp
app.UseDotNetify(cfg => cfg.UseJsonSerializerSettings(new Newtonsoft.Json.JsonSerializerSettings
{
    ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver()
}));
```

**Comment by dsuryd** [comment]
Closing this as resolved by using the above code.
