### ISSUE TITLE
Dispose for Transient instances

### ISSUE THREAD

**Issue by Paulskit** [dsuryd/dotNetify#296]
Problem:
Transient instances don't get disposed on VM dispose

Steps to Reproduce:
1) Register service as Transient
   services.AddTransient<IServiceA, ServiceA>();

2) Inject in ViewModel
```csharp
public class MyViewModel : BaseVM
{
   private readonly IServiceA _serviceA;

   public MyViewModel(IServiceA serviceA)
   {
       _serviceA = serviceA;
   }
}
```

Since it's transient service, it gets created on every instance of `MyViewModel`. However, it doesn't get disposed when model disposed

**Comment by dsuryd** [comment]
Transient and scoped objects have the same lifetime as their connections and not view models, so they will only get auto-disposed when the connection terminates.  If you need it disposed along with the view model instance, explicitly dispose them in the view model's Dispose method override.
