### ISSUE TITLE
Load only necessary JS files for each demo

### ISSUE THREAD

**Issue by dlarosa** [dsuryd/dotNetify#3]
I have been playing around with dotNetify and honestly I am impressed. The architecture is simple, the two-way data binding works great and having most of the business logic on the server side is just what many .NET developers would want. Forgot to mention that the examples are very easy to follow. You must have put a lot of hard work on this project. Thanks.

A small detail I noticed is that all the JS files are being loaded for each demo, that is because the demoApp.js file is bringing all these files regardless whether they are needed or not. Having a  demoApp.js specific file for each example would solve this.

**Comment by dsuryd** [comment]
Thanks for the vote of confidence - much appreciated!  I just uploaded the Typescript version that has some of those JS files moved out of demoApp.js into script tags on the HTML files.
