### ISSUE TITLE
Use dotnetify outside of react components?

### ISSUE THREAD

**Issue by dannief** [dsuryd/dotNetify#30]
All examples that I have seen, demonstrate using dotnetify directly inside react component's getIntialState() function, and it is required to pass the current instance of the component: `dotnetify.react.connect(vmName, component)`

Is it possible to use dotnetify outside of a react component, so that it may be used with any client-side framework or inside an external service for example? Can we get an instance of a vm and dispatch changes and subscribe to server changes outside of react? Or would it just make sense to use signalR directly in that case?

**Comment by dsuryd** [comment]
Yes, it's possible.  The API is customized for React, but you can hack it a bit to this:
```
var myState = {};
dotnetify.react.connect("MyVM", { props: {}}, () => myState, newState => Object.assign(myState, newState) );
```

**Comment by dannief** [comment]
OK. Thanks.

**Comment by dsuryd** [comment]
Since v2.0.6-beta, there's a new wrapper API:

let myState = {};
dotnetify.connect("MyVM", { 
   getState: () => myState,
   setState: newState => Object.assign(myState, newState)
});
