### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by ensemblebd** [dsuryd/dotNetify#302]
DNS renewal issue i suspect, getting a ERR_NAME_NOT_RESOLVED. https://dotnetify.net/
is there a repo containing documentation sources or an alternative?

**Comment by dsuryd** [comment]
Thank you for letting me know; it should be up soon.  All website docs are available here: https://github.com/dsuryd/dotNetify/tree/master/DevApp.ViewModels/Docs

**Comment by dsuryd** [comment]
Took longer than I expected, but the website is fully up again.

**Comment by ensemblebd** [comment]
really really appreciate you and everything you do on this. If I was a rich man I'd invest :P heavily
