### ISSUE TITLE
React and npm packages

### ISSUE THREAD

**Issue by isajan** [dsuryd/dotNetify#310]
Hi, I wonder if you have any plan in future to update react and npm packages both in dotnetify and dotnetify-elements.
Best regards,

**Comment by dsuryd** [comment]
I do, but I have no set timetable.  If you encounter specific incompatibility issues, just provide me with details. I may be able to help.

**Comment by isajan** [comment]
Thanks, it is react version related warnings with npm install. I tried to update all packages to the latest but it is not possible due to peer dependency.

**Comment by dsuryd** [comment]
Updated npm packages to react 18.
