### ISSUE TITLE
no $dispatch in vm

### ISSUE THREAD

**Issue by HengzheLi** [dsuryd/dotNetify#313]
I used below code to get a 'vm' object
```
const { contentItemId } = useParams();
  const { vm, state } = useConnect(vmName, { PriceTickList: []})
  // React.useEffect(()=>{
  //     vm.$dispatch({ Init: { contentItemId: contentItemId }})
  // },[])
  console.info(vm)
```
But there is no $dispatch property in the returned vm. Below is the printed content of vm
![image](https://user-images.githubusercontent.com/491759/188661812-19da83ba-2049-4ead-9ab7-ff0be8aaea49.png)

**Comment by dsuryd** [comment]
It should be listed under `[[Prototype]]: Object`.  And you should check that `vm` is non-null before it's referenced.
