### ISSUE TITLE
Request for generic js library

### ISSUE THREAD

**Issue by danfma** [dsuryd/dotNetify#320]
Hello,

I would like to ask if there is a way to build a generic JS library, so that we can plug in into other frameworks, like Svelte, Solid, etc?

**Comment by dsuryd** [comment]
There's a generic `connect` API that can be used with other JS libraries.  For example, with Angular: https://github.com/dsuryd/dotNetify/blob/master/Demo/Angular/src/app/app.component.ts

**Comment by dsuryd** [comment]
Closing this as answered.
