### ISSUE TITLE
Update NpgSql to lib 7.0.2 in DotNetifyLib.Postgres

### ISSUE THREAD

**Issue by AdamPzpn** [dsuryd/dotNetify#321]
Npgsql 6.0.1 is not working well with PostgreSql 15 and logical replication. 
Update to version 7.0.2 fixed problem with connection for me.

One of changes in library:
https://github.com/npgsql/npgsql/issues/4214
https://github.com/npgsql/npgsql/issues/4216

and more
https://github.com/npgsql/npgsql/milestone/85?closed=1

**Comment by dsuryd** [comment]
The new version with NpgSql v7.0.2 has been published.
