### ISSUE TITLE
The 5.4 version creates several Timeouts without cleaning up

### ISSUE THREAD

**Issue by AlmostADev** [dsuryd/dotNetify#322]
The 5.4 version creates several Timeouts without cleaning up

Recently in my team, we upgraded to version 5.4, and we saw that are several timeouts created each second pointing to some methods like loaded and update methods. I've downgraded to 5.3 and this issue is not happening.

This is running over a React application based on the 16.8.4 version.

![imagen](https://github.com/dsuryd/dotNetify/assets/13564682/2af9696f-648b-4e40-be32-80d0978186bb)

**Comment by dsuryd** [comment]
It's correct that `setTimeout` was introduced in the below code to avoid a possible race condition involving the newly updated state.
https://github.com/dsuryd/dotNetify/blob/a5b850a8715ecf2d68efe4da5061f212c6e76dff/DevApp/src/dotnetify/core/dotnetify-vm.ts#L230

That would explain why you're seeing it on the log.  However, this should not be an issue.
