### ISSUE TITLE
how to get OldRow during an update

### ISSUE THREAD

**Issue by PiotrPlatos007** [dsuryd/dotNetify#323]
I have a problem with the property "OldRow"
Despite setting REPLICA IDENTITY to full.

I get oldRow set to null on every update. Is there something that needs to be configured additionally so that OldRow is set in the application during an update?

**Comment by dsuryd** [comment]
There's an exception with the REPLICA IDENTITY FULL that has been fixed.  You should be able to fetch the old row values now with the latest version.
