### ISSUE TITLE
WebApplication.Core.React IE11 fails

### ISSUE THREAD

**Issue by rjblair** [dsuryd/dotNetify#34]
Requires polyfills:  entry: ["babel-polyfill","./wwwroot/lib/app.js"],

**Comment by dsuryd** [comment]
Added IE polyfills; it should now be working well for IE 11.

**Comment by markau** [comment]
The current fix for Edge/IE11 appears to be the [react-app-polyfill](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill) package.

IE needs the additional `Array.prototype.includes` polyfill:

`<script src="https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.includes"></script>`
