### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by drinkwater99** [dsuryd/dotNetify#35]
You write :

When the connection is established, the class instance will be serialized to JSON and sent as the initial state for the component.

But in the examples in the getInitialSate you are returning an empty state right after the connect - it works obviously but doesn't make sense to me.

**Comment by dsuryd** [comment]
It's an asynchronous operation.  Data won't come right away, so the empty state will be rendered first.  When server responds, state hydrates and causes React to re-render.
