### ISSUE TITLE
Support for new ASP.Net Core 2.0 React.js and Redux VS template

### ISSUE THREAD

**Issue by md8n** [dsuryd/dotNetify#37]
With the new .Net Core SDK VS2017 has a new project template for a ASP.Net Core 2.0 project that builds a React.Js and Redux web application.

I've tried a quick hack with plugging dotNetify into it, but the approach of the standard VS templates (folders, routes, etc.)  is a lot different than the approach taken with the dotNetfy samples.

Any hope of an update to the HelloWorld samples that starts with the new ASP.Net Core 2.0 templates?

**Comment by dsuryd** [comment]
Thank you for the suggestion.  My thought is the "reactredux" template adds a lot more into the mix, e.g. MVC, React Router, Redux, Typescript, while I would rather start with a super-simple template that can do just as much with only React, dotNetify and plain old C# objects.  This is already in the to-do list now that .Net Core 2.0 supports custom templates.

I do like the webpack middleware part, which would be a great update to the existing HelloWorld sample for .NET Core CLI.

**Comment by dsuryd** [comment]
[React SPA template for .NET Core 2.0 is now available.](https://github.com/dsuryd/dotnetify-react-demo-vs2017/tree/master/ReactTemplate)
