### ISSUE TITLE
v2.2.0-pre nuget breaks ASP.NET-Core-Project with net462-TargetFramework

### ISSUE THREAD

**Issue by mumrich** [dsuryd/dotNetify#38]
@dsuryd : first of all thanks for this wonderful framework, I've been searching a long time for such a solution and dotNetify is almost the perfect WebFramework IMHO.

I have encountered a minor issue with the latest nuget-package:
My webproject is a ASP.NET-Core-Project with `<TargetFramework>net462</TargetFramework>`.
The new dependency 
Version v2.2.0-pre of 'DotNetify.SignalR'-Nuget causes compilation-errors in the Startup-Class:
![image](https://user-images.githubusercontent.com/10463536/29754239-8064f3cc-8b81-11e7-9d19-63c1fc68d5c6.png)

I don't fully understand the reason for this new net462-dependency : in my opinion, the original ['DotNetify'-package](https://www.nuget.org/packages/DotNetify/) should be the target for "old" ASP.NET MVC Dependencies, whereas the newer 'DotNetify.SignalR' & 'DotNetify.Core' should be used for ASP.NET Core projects only... or am I missing something here?

**Comment by dsuryd** [comment]
I wanted to put both old and new in the same nuget package, but apparently I didn't take into account ASP.NET Core targetting net462.  Sorted this out with v2.2.1-pre.  Thank you!

**Comment by mumrich** [comment]
Awesome, thanks for the quick reaction! 🥇
I've just tested it, it seems to work!
