### ISSUE TITLE
Code Style: Hungarian notation makes code hard to read and hard to contribute

### ISSUE THREAD

**Issue by dadhi** [dsuryd/dotNetify#4]
Hello,
Overall I was impressed by the library idea and example apps. Then I wanted to test my [DryIoc.SignalR](https://www.nuget.org/packages/DryIoc.SignalR.dll/2.0.0-rc2) package with your library. And though I tried to overcome the code notation couple of times, but it still puts me off.

**Comment by dsuryd** [comment]
Fair enough; let's adopt the coding conventions used by the ASP.NET webstack: http://aspnetwebstack.codeplex.com/wikipage?title=CodingConventions

I welcome other's contributions to progressively update existing codebase to the new conventions.

**Comment by dsuryd** [comment]
Updated coding style.
