### ISSUE TITLE
SignalR version used

### ISSUE THREAD

**Issue by prom3theu5** [dsuryd/dotNetify#43]
Hi There.
Good work on this :)

The (very old - pre RC of even .net core) experimental version of SignalR used for this is no where near production ready though.

I used this version of SignalR live for 6 months on a production system, and would randomly receive alerts from users stating the site was down (Reporting Status code 502).
Upon further investigation it lead me to finally find that SignalR was causing it. Hub transport (Websockets / long polling - didn't matter which transport protocol was used) would just freeze due to the pluggable formatters failing.

See here: https://github.com/aspnet/SignalR/issues/62

This is just a heads up that it'd be better to see if 2.2.1 (signalR) works when targeting .Net 4.6.1 under .Net Standard 2.0, or simply just wait for the Official SignalR release which is coming very soon :)

**Comment by dsuryd** [comment]
Thanks, it's good info.  This is exactly why the .NET Core nugets are still marked pre-release.

**Comment by dsuryd** [comment]
In the latest dotNetify release, the old pre-RC signalR has been replaced with latest signalR .net core 2.0 (alpha2).

**Comment by davesekula** [comment]
Awesome - thanks a lot
I've been using the new signalr alpha's in production myself, on one project, and thusfar they have been pretty cool in terms of stability

**Comment by prom3theu5** [comment]
Awesome - thanks a lot
I've been using the new signalr alpha's in production myself, on one project, and thusfar they have been pretty cool in terms of stability
