### ISSUE TITLE
Typescript definition files

### ISSUE THREAD

**Issue by Brimce** [dsuryd/dotNetify#46]
Hi,
Will you add typescript definition files to the library ?

I've made those files for my need :
[_TypescriptDefinitions.zip](https://github.com/dsuryd/dotNetify/files/1319300/_TypescriptDefinitions.zip)

**Comment by Brimce** [comment]
I also did a BaseView class, this may be usefull.

```javascript
import * as React from 'react';
import * as Dotnetify from "dotnetify";

export abstract class BaseView<P, S> extends React.Component<P, S>{

    readonly vm: Dotnetify.dotnetifyVM;

    constructor(readonly vmName: string, props: any) {
        super(props);

        this.vm = Dotnetify.react.connect(this.vmName, this);
        
        this.state = window.vmStates[this.vmName] || {};
    }

    componentWillUnmount() {
        this.vm.$destroy();
    }

    public $dispatch(iValue: any): void {
        this.vm.$dispatch(iValue)
    };

}
```

**Comment by dsuryd** [comment]
Thank you, I will plan to include a typescript definition file in the next npm release.  The API is still changing,  so the typescript you created will need update.

**Comment by Brimce** [comment]
Perfect !

**Comment by zunath** [comment]
Sorry to comment on a dead issue but I can't seem to locate these typings in version 2.0.8-beta. Has NPM not been updated yet?

**Comment by dsuryd** [comment]
I accidentally left that out.  Thank's for letting me know. You can get them directly from this github under dist/typings, and if there's any issue, feel free to PR.
