### ISSUE TITLE
Reactive Extensions support?

### ISSUE THREAD

**Issue by desarrollo03TR** [dsuryd/dotNetify#47]
Hi! Great project!

I want to develop a project using dotNetify but I want to know if there is support for Reactive extensions.

**Comment by dsuryd** [comment]
DotNetify is a great fit for Rx:
- https://hackernoon.com/real-time-react-chart-with-rx-net-in-minutes-d76bdcf301e4
- https://hackernoon.com/designing-real-time-promise-component-with-react-net-core-9d2ef4162702

**Comment by desarrollo03TR** [comment]
Thanks! 

Is there a list of supported/unsupported c#/.net features for the back-end ViewModel?

**Comment by dsuryd** [comment]
I don't have such list, but your app needs to target at least .NET 4.5 or .NET Standard 1.6.

**Comment by desarrollo03TR** [comment]
Si there a way to create an observable un the VieeModel (c#) and subscribe it in knockout.is?

**Comment by dsuryd** [comment]
I'm not clear on the question. The knockout live chart example in the website can be easily modified to use Rx Observable to push updates to knockout client, if that's what you're asking.

**Comment by desarrollo03TR** [comment]
Yes, something like this. I want to implement some observables in server side and subscribe on client, I need to build a SPA with a lot of "live" UI elements.
