### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by joshua1** [dsuryd/dotNetify#49]
Hi @dsuryd ,
Any chance you would support Vue.js ? the lib seems to be dependent on jQuery. any chance that dependency be optional?

**Comment by dsuryd** [comment]
Vue is on the radar; priority depends on whether there's enough interest. Meanwhile, see issue #30 for possible workaround.

Starting from v2.0.6 beta, dotnetify-react already has optional dependency to full jQuery and depends only on[ jquery-deferred](https://www.npmjs.com/package/jquery-deferred).  In the absence of jQuery, it will use the included [jquery-shim](https://github.com/dsuryd/dotNetify/blob/master/dist/jquery-shim.js).

**Comment by joshua1** [comment]
@dsuryd Thanks for the response, there definitely will be enough interest if there isnt enough already. i will look at #30.

**Comment by desarrollo03TR** [comment]
Vue is really good, it would be nice to have vue support.

**Comment by stevehayles** [comment]
Nowhere to vote as such, but wanted to add a big 'thumbs up' to any potential Vue integration.  

Lots of similarities between Vue and React and the discussions and arguments could go on forever but Vue has a very quick learning curve and is easier to port applications built on similar 'template' style frameworks like Angular.

**Comment by dsuryd** [comment]
I haven't learned Vue yet, but if there's anyone with Vue experience willing to collaborate, we can get this started.   I will need your help creating the equivalent of WebApplication.React but with .vue files and vue material UI.

**Comment by desarrollo03TR** [comment]
I'll try to implement something.

**Comment by desarrollo03TR** [comment]
I think this can help. You can add reactive properties to a Vue instance (a Vue instance is like the main react component) after creation.

For example, this Vue instance:

```
new Vue({
  el: '#app1',
  data: {
	message: 'Hello world',
        age: 23,
  }
})

Can be re-created this way:

```
new Vue({
  el: '#app2',
  data: {
	vm: {}
  },
 created: function() {
 	this.$set(this.vm, 'message', 'Hello world');
 	this.$set(this.vm, 'age', 23);
 }
})
```

The this.$set function can add reactive properties to the Vue instance. 

You can try with this html code:

```
<script src="https://cdn.jsdelivr.net/vue/latest/vue.js"></script>

<div id="app1">
  <div>
	<div>Message: {{ message }}</div>
	<input v-model="message">
	<div>Age: {{ age }}</div>
  </div>
</div>

<div id="app2">
  <div>
	<div>Message: {{ vm.message }}</div>
	<input v-model="vm.message">
	<div>Age: {{ vm.age }}</div>
  </div>
</div>
```

**Comment by desarrollo03TR** [comment]
Well, it works. From the Hello world demo:

```
Mensaje: Hello World!
Server Time: 2018-04-26T17:08:28.1936979-06:00
{
  "message": "Hello world",
  "vm": {
    "state": {
      "$vmId": "HelloWorld",
      "$component": null,
      "$requested": true,
      "$loaded": true,
      "$itemKey": {},
      "User": {
        "Name": "World"
      },
      "Greetings": "Hello World!",
      "ServerTime": "2018-04-26T17:08:28.1936979-06:00"
    }
  }
}
```

But the server time property is not updating.

**Comment by westonsoftware** [comment]
Very interesting, I'd like to try the same thing with Vue, any progress on this?  (I really don't know much React but I did do some Vue recently)

**Comment by jaredthirsk** [comment]
Hi, it has been a couple of months since last comment -- wondering if anyone has started work on this.  I'm leading my .NET team into Vue because of its ease of (incremental) adoption and dotNetify could also be a good fit.

Vue stack that I love, FWIW: Vue Vuex Quasar.  I wonder if Vuex would make any sense for dotNetify -- anyone have thoughts?

**Comment by westonsoftware** [comment]
Hi, I just spent the last week learning Quasar + Vuex and I think it's pretty awesome.  I could see doing something like "quasar new store <controller>" and then figuring out how to dotnetify that.  Worth looking into at least.

**Comment by artruder** [comment]
Noticed its moved to the planned state at the roadmap, Dsuryd thank you :)
Looking for vue support! 

I'll would like to start a new project, but not sure it is worth to wait some months for vue or just start with react? There is any chance to be supported at this year?

**Comment by dsuryd** [comment]
Thank you, the target is sometime next month.

**Comment by dsuryd** [comment]
Vue support is provided starting v3.2.
