### ISSUE TITLE
Absence of Unit Tests

### ISSUE THREAD

**Issue by dadhi** [dsuryd/dotNetify#5]
Example apps are obviously great. But Unit Tests will help to structure your code for extensibility and maintainability, in addition to quality check.

As I wanted to introduce DI into your library I saw a lot of statics, which is hard to DI. If unit tests were present, I believe this would've be better.

**Comment by dsuryd** [comment]
Thank's for pointing it out; (automated?) unit testing is sorely needed.  How best to refactor the statics to fit in the DI?

**Comment by dadhi** [comment]
Hard to tell in general. I'll probably try to refactor small part, rename things, add DI to some extent, and put some unit tests. Then you could look at result PR and say what you think. Hopefully next week.

**Comment by dsuryd** [comment]
Code's been refactored to support DI and demo code added.  Written unit tests with good coverage on the core library.

**Comment by dadhi** [comment]
Great! You rock. Now no complaints to start using the library.
