### ISSUE TITLE
ETA on SignalR Alpha 2 Release?

### ISSUE THREAD

**Issue by acronoah** [dsuryd/dotNetify#50]
I have an application in development for my workplace that makes significant use of dotnetify.  I see commits in master related to upgrading to the latest version of SignalR.  Is there a way to use this work other than syncing the head of master?  What work remains?  I can help...

**Comment by dsuryd** [comment]
Thank you for using dotnetify!  ETA is this weekend.  It's code complete, I just need to test in various configuration and to update the documentation.

**Comment by dsuryd** [comment]
[It's released](https://github.com/dsuryd/dotNetify/releases/tag/v2.0.7-beta%2F2.2.2-pre)!
