### ISSUE TITLE
Possibilty to adapt another MVVM library?

### ISSUE THREAD

**Issue by desarrollo03TR** [dsuryd/dotNetify#51]
I'm starting a dotNetify project, in my apps I'm using ReactiveUI as MVVM library and I love it. Dotnetify is reactive, and ReactiveUI is reactive too, could it be possible to adapt the RxUI library to dotNetify?

ReactiveUI implements the INotifyPropertyChanged.

**Comment by dsuryd** [comment]
Thank's for the suggestion; this will definitely be considered.

**Comment by desarrollo03TR** [comment]
I'll try to help, if I can get something, I'll post it.

**Comment by KeilFelix** [comment]
I would like to support this issue. I am currently extending BaseVM with my own ViewModelBase that has other features. It nags me that I have to derive from BaseVM to use Dotnetify.
A good option would be to have a class where the ViewModels can be registered instead of derived.
Another possibility would be to have a constructor in BaseVM that takes another ViewModel as Object and reads the properties via System.ComponentModel.TypeDescriptor and wires them to BaseVM properties.

**Comment by desarrollo03TR** [comment]
I think that using interfaces will be easier, for example:

public interface IBaseVM : INotifyPropertyChanged, IDisposable
{
    void PushUpdates();
}

**Comment by KeilFelix** [comment]
Sorry to disagree. The PushUpdates function should not be implemented in other IBaseVMs. There is no need for different variants/other behaviour. 

What DotNetify needs to know about the custom ViewModels are just the properties (Commands included). How do you handle this by an interface? 
Currently this is done by reflection and callermembername.
This can be changed to System.ComponentModel.TypeDescriptor that is used in WPF to make Databinding/INotifyPropertyChanged work and is also included in Core 2.0.

**Comment by desarrollo03TR** [comment]
is not it supposed that INotifyPropertyChanged is notifying the property names?

What about this:

public interface IBaseVM : INotifyPropertyChanged, IDisposable
{
    event EventHandler RequestPushUpdates;
}

I'm inspecting the dotNetify code.

**Comment by dsuryd** [comment]
Good discussion! I've always wanted to move away from class inheritance, and to replace it with just a marker interface and extension methods (similar to DotNetify.IRoutable).  Keil's 2nd option seems viable: basically having a shadow BaseVM, known only by the VMController, that encapsulates and interacts with the actual view model.  I would try to avoid using TypeDescriptor if I could, since [it has even more overhead than Reflection](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/optimizing-performance-data-binding).

**Comment by desarrollo03TR** [comment]
I replaced all the BaseVM references with the IBaseVM interface and it looks like it is still working.

**Comment by KeilFelix** [comment]
@dsuryd Thanks for the interesting article. I browsed the reference source and in PropertyPath there are indeed different strategies to resolve the property. Maybe it is the best way to do it the same way?

@desarrollo03TR can you make a branch/fork with your changes to dotnetify? I would like to see where you are going.

**Comment by desarrollo03TR** [comment]
@KeilFelix I'm testing the different examples, I need to be sure that everything will work. The Hello World and the Controls Types are working fine. After this, I'll create a  fork.

It is just changing every BaseVM reference for IBaseVM,, then, I create  a new class called "ReactiveVM", and change the demos ViewModels from BaseVM to ReactiveVM.

**Comment by desarrollo03TR** [comment]
Well, I've translated every single example using my ReactiveVM class  implementing the IBaseVM interface, and everything is working fine, even commands (using ReactiveUI ReactiveCommand object), I'm really happy. I'll create a fork soon, I just need to apply the changes to the core version of the framework.

Thanks to Dicky, Dotnetify is great!

**Comment by KeilFelix** [comment]
Great! I still think the interface is the wrong direction. Don't want to offense. Hope to see your code soon!

**Comment by desarrollo03TR** [comment]
@KeilFelix No offense 😉 what I like about interfaces is that you can create mixins using extending methods.

Also, there is not need to change a lot of dotNetify (and projects using dotNerify) code.

**Comment by dsuryd** [comment]
Cool, thx for exploring this!  I'm currently working on dotnet new template, but will jump on this soon.  My thought is to allow for the view model to just straight inherit from ReactiveObject, or any class that implements INotifyPropertyChanged.  Only if it needs to use dotNetify API like PushUpdates then the view model is required to implement a specialized interface like this:
```c#
public interface IPushVM
{
   event EventHandler RequestPushUpdates;
}
```
```c#
public class LiveChartVM : ReactiveObject, IPushVM
{
   public event EventHandler RequestPushUpdates;

   private void PushUpdates() => RequestPushUpdates?.Invoke(this, null);
}
```

**Comment by desarrollo03TR** [comment]
@dsuryd Great idea!, I'll try to implement it that way in my fork and post update here.

**Comment by desarrollo03TR** [comment]
The form (from my personal account): https://github.com/lrhmx/dotNetify I'm rewriting the examples using ReactiveUI.

I'm sure Dicky will make a better job.

**Comment by dsuryd** [comment]
This feature has been implemented in the latest master branch.  You can now register view models that are not subtypes of BaseVM, as long as they implement INotifyPropertyChanged.  See examples in [the UnitTests folder](https://github.com/dsuryd/dotNetify/blob/master/ASP.NET%20Core%20Demo/UnitTests/LiveChartNoBaseVMTest.cs). 

You can also override default serializer by implementing [ISerializer](https://github.com/dsuryd/dotNetify/blob/master/DotNetifyLib.Core/BaseVM/ISerializer.cs).

**Comment by dsuryd** [comment]
This feature is now part of nuget v2.3.0-pre release.
