### ISSUE TITLE
Polymer sample code? 

### ISSUE THREAD

**Issue by desarrollo03TR** [dsuryd/dotNetify#52]
Where can I find the polymer code? http://dotnetify.net/polymer

**Comment by dsuryd** [comment]
It's inside the ASP.NET Demo/WebApplication.Knockout.  It uses these plugins: [dotnetify.binder.js](https://github.com/dsuryd/dotNetify/blob/master/ASP.NET%20Demo/WebApplication.Knockout/Scripts/dotnetify.binder.js) and [dotnetify.binder.polymer.js](https://github.com/dsuryd/dotNetify/blob/master/ASP.NET%20Demo/WebApplication.Knockout/Scripts/dotnetify.binder.polymer.js).  Note that the plugins were experimental and was never part of any release.
