### ISSUE TITLE
Hello World Documentation Out of Sync With Demo

### ISSUE THREAD

**Issue by joelcdoyle** [dsuryd/dotNetify#55]
EDIT: Actually there are few things about [the demo](http://dotnetify.net/react/create-react-app) that make me scratch my head. As it is, [the demo](http://dotnetify.net/react/create-react-app) does not work. React app in browser shows "Server time is: ". Console log shows:

`Error: Failed to start the connection. SyntaxError: Unexpected token H in JSON at position 0`

This is due to this block in Startup.cs:
```
      app.Run(async (context) =>
      {
        await context.Response.WriteAsync("HelloWorld server");
      });
```
The browser is receiving "HelloWorld server" and expecting it to be JSON.

[Current tutorial docs for Hello World app](http://dotnetify.net/react/create-react-app) are not the same as the example demo:

HelloWorld.cs
```
using System;
using System.Threading;
using DotNetify;

namespace helloworld
{
    public class HelloWorld : BaseVM
    {
        private Timer _timer;
        public string Greetings => "Hello World!";
        public DateTime ServerTime => DateTime.Now;

        public HelloWorld()
        {
            _timer = new Timer(state =>
            {
                Changed(nameof(ServerTime));
                PushUpdates();
            }, null, 0, 1000);
        }
        public override void Dispose() => _timer.Dispose();
    }
}
```

`ServerTime` should be a string, and `DateTime.Now` should be converted to a string:

```
public string ServerTime => DateTime.Now();
```

**Comment by joelcdoyle** [comment]
My issue was needing to install .NET Core SDK 2.0

**Comment by dsuryd** [comment]
You are correct that the create-react-app demo steps in the website are outdated; it still refers to the previous version.  I'll update it tonight. Thx!
