### ISSUE TITLE
Calling a javascript function from c#

### ISSUE THREAD

**Issue by desarrollo03TR** [dsuryd/dotNetify#57]
Is there a way to call a javascript function (view) from c# (viewmodel) and get the return value?

**Comment by dsuryd** [comment]
It has to be in an asynchronous and decoupled manner: vm sets a property, the view observes the change, and affects another property.  If you're using Knockout, see [the job queue example](http://dotnetify.net/index/JobQueue).

**Comment by desarrollo03TR** [comment]
Thanks, I need a response from the user, for example "yes/no", and other interactions.

I'm doing the property changing for messages and warnings, but I need a better way for dialogs with responses.

**Comment by dsuryd** [comment]
I'm not clear on the issue you're facing, but you will have to write javascript/typescript code to launch dialogs.  Of all the examples I've written (both React and KO) that have complex UI; is there one that's close to what you need?  But one thing I have to say, a view model that's directly calling the view is a violation of the MVVM principle, and won't be supported by dotNetify.

**Comment by desarrollo03TR** [comment]
I dont want to call the view, I want to avoid it, let me explain:

ReactiveUI has a component called "Interactions", in your ViewModel  you declare an Interaction like this:

`public Interaction<string, bool> Confirm { get; private set; } `

And you can use it:

`var delete = await Confirm.Handle(fileName);`

This way the ViewModel is not making any call to the View.

In the View side you define the Interaction behavior, for example:

```
Confirm .RegisterHandler( async interaction =>{
    var deleteIt = await alert( "Confirm Delete", $"Are you sure you want to delete '{interaction.Input}'?",  "YES","NO");
    interaction.SetOutput(deleteIt);
}));
```
And on any platform you can re-define the interaction behavior using the platform specific methods. This is how the ViewModels can request information from the user, and the View will "translate" the interaction.
