### ISSUE TITLE
Access current HTTPContext from IHttpContextAccessor

### ISSUE THREAD

**Issue by assurancetourix** [dsuryd/dotNetify#59]
Hello,

Thanks for your great solution.
I may have found something curious, you may help me with. In one of my BaseVM class, I want to access the current context, I use IHttpContextAccessor this way:

```

public LogQuery(IHttpContextAccessor Accessor, ILogger<LogQuery> Log)
        {
            _log = Log;
            _accessor = Accessor;
            var context = _accessor.HttpContext;
            var url1 = context.Request.Path.ToString();
            var url2 = context.Request.GetDisplayUrl();

            _log.LogInformation("contextpath1: " + url1);
            _log.LogInformation("contextpath2: " + url2);
        }


```
In my log file I get:

> contextpath1: /dotnetify 
> contextpath2: http://localhost:61201/dotnetify?id=2e179181-9023-4afc-a130-938a403824ec

In the Startup class, the path is correct. Would you know how it is possible to get the actual url of the request ?

I use 2.2.2-pre.

Thanks.

**Comment by dsuryd** [comment]
Hi, dotNetify runs on SignalR pipeline, which has its own [context](https://github.com/aspnet/SignalR/blob/5dceaa81499c43afcad06349ad3fdda0feb92d84/src/Microsoft.AspNetCore.SignalR.Core/HubCallerContext.cs).  There's no accessor API as far as I know,  but you can have access to it if you write dotNetify [middleware](http://www.dotnetify.net/react/Middleware) or [filter](http://www.dotnetify.net/react/Filter).  The URL is probably somewhere inside the Connection property.

**Comment by assurancetourix** [comment]
Hi Dicky,
Thanks very much for your explanations, I will give a try with middleware.

**Comment by dsuryd** [comment]
If you don't mind me asking, what's the use case you're trying to accomplish?
