### ISSUE TITLE
all demo samples in selfhosted owin-nancy-dotNetify

### ISSUE THREAD

**Issue by Davtomas** [dsuryd/dotNetify#6]
I am trying to extend the nancy selfhosted example to other demo samples e.g. TreeView.html.

I could not get the data binding to work. Perhaps I miss something.

**Comment by dsuryd** [comment]
I just updated the Nancy demo solution with some of the examples.  Other than updating the paths in the HTMLs, some other things to pay attention to:
- At startup, register the view model assembly by calling VMController.RegisterAssembly.
- TypeScripts in Visual Studio class libraries don't seem to be well supported.  Make sure the compiled JS files are actually produced and copied to the bin folder.  I put some notes about this in HowToCreateSolution.md.

**Comment by Davtomas** [comment]
I just added one line ( HelloWordVM) and I get this error. I wonder how to decouple the various ViewModels in your demo sample. 

`VMController.RegisterAssembly(typeof(HomeModule).Assembly);
VMController.RegisterAssembly(typeof(HelloWorldVM).Assembly);`

Additional information: ERROR: View model 'AFITop100VM' was already registered by another assembly!

**Comment by Davtomas** [comment]
I check through the updated Nancy example. I can only find one line 

`VMController.RegisterAssembly(typeof(ExamplesLibrary.TreeViewVM).Assembly);`

Yet, your selfhosted console is able to find all the VMs  Why?

Also, I see that for GridView, you have created a resource dll. Very interesting.

**Comment by dsuryd** [comment]
Those view models are all in the same assembly, and you only need to register the assembly just once. 

The Gridview example is using the resource file to demonstrate localization.

**Comment by dsuryd** [comment]
Perhaps it's clearer to state it like this:
``
VMController.RegisterAssembly(System.Reflection.Assembly.Load("ExamplesLibrary"));
``

**Comment by Davtomas** [comment]
The concept is great, the implementation is not intuitive. 
The html file's link to css and js seems not relevant to their folder structure. 

Are both statement similar? can I arbitrary put data-main to any script I like? or it should be the last Script statement?
 
`<script src="/Scripts/CodeBehind/CompositeView.js"></script>
   <script src="/Scripts/require.js" data-main="/Scripts/app"></script>`

`<script src="/Scripts/CodeBehind/CompositeView.js"  data-main="/Scripts/app"></script>
   <script src="/Scripts/require.js"></script>`

**Comment by Davtomas** [comment]
In which part of the code that you instruct to look for 
`ExamplesLibrary.resources.dll` in ja-jp directory? in the context of selfhosting

**Comment by dsuryd** [comment]
Any contribution on how to make this project more usable is certainly welcome.  There are various different technologies at work here and I tried my best to integrate them and provide consistent user experience but I'm sure there are a lot of room for improvements.

The data-main attribute belongs to require.js tag, which is a library used for asynchronously loading other javascripts.

Look at the English/Japanese button implementation in the HTML, you'll see they send the culture code when clicked through command binding. Look at the view model, the ResourceCulture property receives it, then call .NET API to switch the current culture.  The .NET framework handles the rest, such as locating the correct resource module in the bin folder.

**Comment by Davtomas** [comment]
Our discussion will help others to learn more of your thinking behind the design. My main interest is to deploy the solution in linux through mono. I hope your library will eventually be included in .NET core or OpenSharp

**Comment by dsuryd** [comment]
Just FYI, ran the self-hosted binaries compiled with Xamarin Studio on a Ubuntu VM.  After correcting capitalization of a file path, it worked fine.  Saw OWIN authentication exception being reported, but looks like a known SignalR issue on Mono and didn't hinder the execution.  Localization wasn't working, though.

**Comment by Davtomas** [comment]
Thanks for trying that. Moving opensource .NET project to mono and linux opens "scale out" opportunity.
