### ISSUE TITLE
Support for Bridge.net in the future?

### ISSUE THREAD

**Issue by desarrollo03TR** [dsuryd/dotNetify#61]
I'm learning about Bridge.net, a c# to javascript compiler, and it support React (writing React components using c#).

It would be really interesting if the React dotNetify  API could be used in c# via Bridge.net.

**Comment by dsuryd** [comment]
Not that familiar with the tool, but it seems that there would be pretty serious downsides to developer experience: you're replacing very expressive and declarative JSX syntax that's highly optimized for UI component-based development with something that would make your front-end codebase much more verbose and clunky; you can't use the wonderful webpack hot reload capability; you probably can't take advantage of all those awesome components and tools the React community has produced; and you're at the mercy of the compiler for optimizing your code and keeping up with the latest React library update.
