### ISSUE TITLE
dotNetify doesn't work in IE11

### ISSUE THREAD

**Issue by TFTomSun** [dsuryd/dotNetify#63]
When the web app is started The following error message pops up:

Unhandled exception at line 6858, column 13 in https://unpkg.com/dotnetify@2.0.7-beta/dist/signalR-netcore.js
0x800a1391 - JavaScript runtime error: 'Promise' is undefined occurred

I've read that this is a know issue and it seems that there's a solution, but I didn't understand how to workaround or solve the issue.

**Comment by dsuryd** [comment]
IE 11 needs polyfill for Promise object.  There's an easy fix; just add this script tag:

`<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.js"></script>`

**Comment by TFTomSun** [comment]
Thanks, that solved the issue.
