### ISSUE TITLE
Using client side state Manager 

### ISSUE THREAD

**Issue by joshua1** [dsuryd/dotNetify#64]
It seems like using a client side state manager like redux, mobx or vuex (for vue) is not the direction of vuex, each componnet would have to instantiate a connection using its own state object. what about situations where you share client state across component and want the update to a state property to reflect across components using this state without the continuous connect / destroy life cycle each component have to maintain. would be nice to centrally manage connection and state (e.g using plugins in vue)

**Comment by dsuryd** [comment]
I've written my thoughts about this [on the website](http://www.dotnetify.net/react/DataFlow).  Associate dotNetify view models only with container components.  You could connect a root-level view model to any client-side state manager like Redux Store to achieve what you want.
