### ISSUE TITLE
Deploy on iOS?

### ISSUE THREAD

**Issue by kmcclive** [dsuryd/dotNetify#65]
I'm really excited about the work being done with dotNetify.  Today, I was able to connect a react-native app running in an iOS simulator to an ASP.NET Core back-end.  What is not clear to me is whether something like this can actually be deployed to an iOS device.  I have a need to develop a cross-platform app that works completely offline and reuses C# code that has already been written.  How would I go about starting the ASP.NET core back-end from the front-end?  How would I package that all up as an app?  Is this even possible?

**Comment by dsuryd** [comment]
No, unfortunately - this cannot be deployed as a completely offline mobile app.  Only Xamarin can run C# code inside iOS or Android.

**Comment by kmcclive** [comment]
OK, thanks for that clarification.  @dsuryd Do you know if anyone has successfully launched a react-native UI from Xamarin?

**Comment by dsuryd** [comment]
Xamarin uses XAML-based UI.  React and Xamarin don't mix.
