### ISSUE TITLE
Signalr negotiation failure

### ISSUE THREAD

**Issue by OracPrime** [dsuryd/dotNetify#66]
I've just upgraded a working dotnetify project from aspnetcore 1.0 to 2.0.  Whilst the main application is working fine, the signalr bits (which I'm only doing via dotnetify) are failing.

In particular I'm getting "Error during negotiation request".  And the response to the negotiation request seems to be the default view.  Which makes me think that something is not routing signalR requests to the right place.

The request is http://localhost:5000/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22dotnetifyhub%22%7D%5D&_=1512601154462

which decodes to having [{"name":"dotnetifyhub"}] as the parameters, but it gets the default view back.

So I'm assuming there's something in the Startup not working.  Just in case it's Cors, I've got a startup that looks like this:

      services.AddSignalR();
      services.AddCors(o =>
      {
        o.AddPolicy("Everything", p =>
        {
          p.AllowAnyHeader()
              .AllowAnyMethod()
              .AllowAnyOrigin();
        });
      });
      services.AddDotNetify();
      // Add framework services.
      services.AddMvc();

but it still doesn't work.

Any suggestions?

Thanks.

**Comment by dsuryd** [comment]
Hi, you seem to have the older signalR v2.x client talking to the new signalR .net core server.  They're not compatible.  Please follow the [upgrade steps here](https://github.com/dsuryd/dotNetify/releases/tag/v2.0.7-beta%2F2.2.2-pre).  Let me know if you still run to problems.

**Comment by OracPrime** [comment]
Since I'm using .NetCore 2.0 at the server end, I had assumed that the only change I needed was the
UseSignalR(route => route.MapDotNetifyHub());
line, which I've done.  Is one of the other steps required? It reads as if the other points you highlight are all ways of overriding defaults, and I had assumed the defaults would work.

Thanks for the speedy response!

**Comment by dsuryd** [comment]
You'll need to upgrade dotNetify client to ^v2.0.7, which uses signalR .net core client by default.

**Comment by OracPrime** [comment]
Ah.  My package manager is only offering me ^v2.0.8-beta - should that be ok?

**Comment by dsuryd** [comment]
Yes.

**Comment by OracPrime** [comment]
So having refreshed everything, restarted webpack, etc, etc, I'm now getting

Error: Failed to start the connection. SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

because the client is requesting /dotnetify and my backend is just giving back the default singlepage app response instead of the JSON.  So something is not registering the route correctly.  I'm using DotNetify.SignalR 2.2.2-pre (Oct 22).  Which has installed Microsoft.AspNetCore.SignalR 1.0.0-alpha2-final as a dependency.

**Comment by dsuryd** [comment]
Sounds like the server didn’t correctly handle the signalR message.  Could you compare your Startup.cs with the one in the HelloWorld project in the dotnetify-react-demo-vs2017 github?

**Comment by OracPrime** [comment]
The only difference is that I have Mvc in the mix:

      app.UseMvc(routes =>
      {
        routes.MapRoute(
                  name: "default",
                  template: "{controller=Home}/{action=Index}/{id?}");

        routes.MapSpaFallbackRoute(
                  name: "spa-fallback",
                  defaults: new { controller = "Home", action = "Index" });
      });

When I commented out this code and restarted the server, the browser which had been sitting in a loop trying to connect to signalR suddenly connected.  However doing a page refresh then gave me an empty page as my Mvc was toast.

However this has led me to the solution.  If you are using Mvc then the app.UseSignalR and app.UseDotNetify **must come before app.UseMvc**
