### ISSUE TITLE
Access to the client info would be nice

### ISSUE THREAD

**Issue by OracPrime** [dsuryd/dotNetify#69]
It would be quite nice to be able to get hold of some client information: I've got a nice working website now (thanks, dotNetify!) but I'd quite like to log what sort of use it is getting.  I can do the dynamic "what they're doing with it" bit in the VM updates, but I'd quite like a way of getting at, say, the initial request that instantiates the VM for things like IP, browser type, screensize, etc.

But I can't see a way of doing this.  Is there one?  If not, could there be one?  Maybe make InitialRequest a property on BaseVM?  Althouhg I can't help feeling there should be a nicer way.

**Comment by dsuryd** [comment]
Would Google Analytics meet the need? 
If you insist on collecting the data yourself, a clean way would be to pass them in the headers:
```
this.vm = dotnetify.react.connect("MyVM", this, {
   headers: { ClientInfo: "..." }
});
```
And add a custom middleware ([see doc](http://www.dotnetify.net/react/Middleware)s) to intercept the request and extract the info from the `Headers` property of the `DotNetifyHubContext`-typed argument.

**Comment by OracPrime** [comment]
I don't believe Google Analytics would give me the signalrR interactions - ie. the data as to what it is being used for.  So I could see who was accessing it with what IP, browser, etc.  And personally I could log the signalR interactions.  But I can't see how I could tie the two together (except by date/time which wouldn't work for concurrent access).

Your code snippet looks like your suggesting I access the headers in javascript - but I don't think that's possible (without outrageous hacks).  Looks like custom middleware is the way to go - I'll hit the docs...

**Comment by OracPrime** [comment]
Trying to stich up some controller-request middleware (which has the headers to get the ip address) with the signalr middleware (which invokes the VM instance) is a bit of a nightmare.

So what I've done (which requires an additional round-trip) but which is considerably simpler than the above) is to just have a separate controller method which uses HttpContext.Connection.RemoteIpAddress to get the remote IP address, which I then set on the VM using a property:

`axios.default.get('/home/clientinfo').then(response => this.setState({ ClientIp: response.data }));`

Which is one extra round-trip, but the IP is not available client-side (as it is before NAT etc).  It's not perfect, but it will do.
