### ISSUE TITLE
How to get querystring?

### ISSUE THREAD

**Issue by forconz** [dsuryd/dotNetify#70]
I do not have a idea to design vm class, the BaseVM only has RequestPushUpdates, do not have Request, so I can not use Request.QueryString.

How to get querystring from Url?

**Comment by dsuryd** [comment]
Use javascript to extract the query string from the URL, then pass it as an initial property value to the vm when you connect, e.g.:  `dotnetify.react.connect("MyVM", this, {vmArg: { MyProperty: queryArg  }});`

**Comment by forconz** [comment]
How to  extract the query string from the URL by Knockout JS?
e.g.: dotnetify.ko.connect("MyVM", this, {vmArg: { MyProperty: queryArg }});  ???

I did not find dotnetify.react in dotnetify.js,dotnetify-hub.js,dotnetify.router.js,dotnetify.binder.js

**Comment by forconz** [comment]
If I browse the url http://dotnetify.net/index/HelloWorld?firstname=qshello&lastname=qsworld
the query string of url is: firstname=qshello&lastname=qsworld

How can I write some script code in HelloWorld.html? and how can I write some C# code in HelloWorldVM.cs?

My project use Knockout JS.

**Comment by dsuryd** [comment]
Hi, I didn't realize you're using Knockout.  The syntax is different from React.   Basically, you pass the parameters to the VM using 'data-vm-arg' attribute on the HTML element that has data-vm' attribute. 
 Look at the example for this issue: https://github.com/dsuryd/dotNetify/issues/7

**Comment by forconz** [comment]
Many thanks, but I write some code for extract the query string, it is work well
http://dotnetify.net/index/HelloWorld
I add some code to the demo.

\dotNetify-nuget_v.2.3.1-pre\ASP.NET Core Demo\WebApplication.Knockout\Views\HelloWorld.html
    <script>
        function urlArgs() {
            var args = {};
            var query = location.search.substring(1);
            var pairs = query.split("&");
            for (var i = 0; i < pairs.length; i++) {
                var pos = pairs[i].indexOf("=");
                if (pos == -1) {
                    continue;
                }
                var name = pairs[i].substring(0, pos);
                console.log(name);
                var value = pairs[i].substring(pos + 1);
                args[name] = value;
            }
            return args;
        }

        var HelloWorldVM = (function () {
            function HelloWorldVM() {
                // http://localhost:51880/demo/HelloWorld?firstname=qshello&lastname=qsworld
                var queryString = urlArgs();
                this._firstName = queryString.firstname; // qshello
                this._lastName = queryString.lastname; // qsworld
            }
            HelloWorldVM.prototype.$ready = function () {
                var vm = this;
                var person = { FirstName: vm._firstName(), LastName: vm._lastName() };
                if (!person.FirstName || !person.LastName)
                    return;

                vm.ExtractQueryString(person);
            };
            return HelloWorldVM;
        }());
    </script>

\dotNetify-nuget_v.2.3.1-pre\ASP.NET Core Demo\ViewModels\HelloWorldVM.cs
        public ICommand ExtractQueryString => new Command<string>(arg =>
        {
            var queryEmployee = (EmployeeInfo)JsonConvert.DeserializeObject(arg, typeof(EmployeeInfo));
            FirstName = queryEmployee.FirstName;
            LastName = queryEmployee.LastName;
        });

it work well.

**Comment by forconz** [comment]
http://localhost:51880/demo/HelloWorld?firstname=qs-hello&lastname=qs-world

input of First name show text: qs-hello
input of Last name show text: qs-world
Full name is qs-hello qs-world

if I change value of First name:qs-hello123 and value of Last name:qs-world345
Full name is qs-hello123 qs-world345

![helloworld](https://user-images.githubusercontent.com/9990289/35350309-7d08eb4e-0178-11e8-9851-978c08a58d45.png)

it work well. so good!

**Comment by forconz** [comment]
I can parse a query string into an object
`
        function urlArgs() {
            var args = {};
            var query = location.search.substring(1);
            var pairs = query.split("&");
            for (var i = 0; i < pairs.length; i++) {
                var pos = pairs[i].indexOf("=");
                if (pos == -1) {
                    continue;
                }
                var name = pairs[i].substring(0, pos);
                console.log(name);
                var value = pairs[i].substring(pos + 1);
                args[name] = value;
            }
            return args;
        }
`
The code work well.

I readed the link #7 : https://github.com/dsuryd/dotNetify/issues/7
but I had not any idea to pass object of query string on the HTML?

<div class="jumbotron" data-vm="HelloWorldVM" data-vm-arg="urlArgs()">
it did not work well.

**Comment by forconz** [comment]
@dsuryd could you write demo for query string? pass object of query string on the HTML and VM.cs.
I think my code is stupid, I can not decrease the amount of JavaScript code I need to write on the front end. 
How to reduce the amount of code to maintain by fostering reuse?

Because many html page of my admin project need to parse query string.

**Comment by dsuryd** [comment]
Here you go:

```html
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8" />
   <title>DotNetify-Knockout</title>
   <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
   <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
   <script src="https://unpkg.com/dotnetify@2.0.8-beta/dist/knockout.mapping-latest.js"></script>
   <script src="https://unpkg.com/dotnetify@2.0.8-beta/dist/signalR-netcore.js"></script>
   <script src="https://unpkg.com/dotnetify@2.0.8-beta/dist/dotnetify-hub.js"></script>
   <script src="https://unpkg.com/dotnetify@2.0.8-beta/dist/dotnetify.js"></script>

   <script>
      $(document).ready(function () {
         var getQueryString = function (field) {
            var string = new RegExp('[?&]' + field + '=([^&#]*)', 'i').exec(window.location.href);
            return string ? string[1] : null;
         };
         var args = { FirstName: getQueryString('firstName'), LastName: getQueryString('lastName') };
         for (var name in args)
            if (!args[name])
               delete args[name];
         $("[data-vm]").attr("data-vm-arg", JSON.stringify(args));
      });
   </script>
</head>
<body>
   <div data-vm="HelloWorldVM">
      <div>
         <label>First name:</label>
         <input type="text" data-bind="value: FirstName" />
      </div>
      <div>
         <label>Last name:</label>
         <input type="text" data-bind="value: LastName" />
      </div>
      <div>
         Full name is <span data-bind="text: FullName" />
      </div>
   </div>
</body>
</html>
```

**Comment by forconz** [comment]
`<script>
var QuoteViewModel = (function () {
    function QuoteViewModel() {
        var qs = getQueryString();
        this._id = qs.Id;
    }
    QuoteViewModel.prototype.$ready = function () {
        var vm = this;
        var args = { Id: vm._id() };
        if (args.Id)
        { 
            $("[data-vm]").attr("data-vm-arg", JSON.stringify(args));
        }
    };`

I press F12, and I get the html such as:
<div class="row" data-vm="QuoteViewModel" data-vm-arg="{&quot;Id&quot;:&quot;512&quot;}">
data-vm-arg="{"Id":"512"}"

$("[data-vm]").attr("data-vm-arg", JSON.stringify(args));
the code work well.

QuoteViewModel.cs
`
        /// <summary>
        /// This property receives the ID of the updated item.
        /// </summary>
        public int Id
        {
            get { return Get<int>(); }
            set
            {
                Set(value);

                if (value > 0)
                {
                    var quote = _repository.SelectQuoteAsync(value).GetAwaiter().GetResult();
                    //Changed(() => EditedItem);  // Update the details.
                }
            }
        }
`
In QuoteViewModel.cs, the Id property can not get the value from html.
How can I do for QuoteViewModel.cs??? I hava not any idea to do it.

**Comment by dsuryd** [comment]
There are 2 ways you can pass the arguments back to the view model, either through the code behind like what you did before I told you about "data-vm-arg", or with the "data-vm-arg".  But you cannot mix both.  

I suggest you just use the "data-vm-arg" tag because it doesn't require you to create the code-behind, it only needs a small script at the beginning of each page to extract the query string arguments and populate the tag.   The HTML example I gave you works - it only needs small modification to achieve what you needed to do.

**Comment by forconz** [comment]
Many thanks.

`
<script> var QuoteViewModel = (function () { function QuoteViewModel() { var qs = getQueryString(); this._id = qs.Id; } QuoteViewModel.prototype.$ready = function () { var vm = this; var args = { Id: vm._id() }; if (args.Id) { $("[data-vm]").attr("data-vm-arg", JSON.stringify(args)); } };
`
The code presented above assumes that vmArg is undefined.
\dotNetify-nuget_v.2.3.1-pre\ASP.NET Core Demo\WebApplication.Knockout\wwwroot\lib\dotnetify.js
line 644
var vmArg = self.element.attr("data-vm-arg");
vmArg is undefined

\dotNetify-nuget_v.2.3.1-pre\DotNetifyLib.Core\VMController.cs
line 306
if (vmArg is JObject)
vmArg is null

So, I carefully watched every detail of the dom.
\dotNetify-nuget_v.2.3.1-pre\DotNetifyLib.SignalR\DotNetifyHub.cs

line 109
public void Request_VM(string vmId, object vmArg)
vmArg is null

\dotNetify-nuget_v.2.3.1-pre\DotNetifyLib.Core\VMController.cs
line 265
protected virtual BaseVM CreateVM(string vmId, object vmArg = null, string vmNamespace = null)
vmArg is null

But html code is:
<div class="jumbotron" data-vm="HelloWorldVM">

and data of VM from server send to html client, 
html code is:
<div class="jumbotron" data-vm="HelloWorldVM" data-vm-arg="{&quot;FirstName&quot;:&quot;qs-hello&quot;,&quot;LastName&quot;:&quot;qs-world&quot;}">

Ok , I can not write 
`$("[data-vm]").attr("data-vm-arg", JSON.stringify(args));`
in QuoteViewModel.prototype.$ready.

I look back this link:
`
        $(document).ready(function(){
            var qs = getQueryString();
            var args = { FirstName: qs.firstname, LastName: qs.lastname };
            if (args.FirstName || person.LastName) {
                $("[data-vm]").attr("data-vm-arg", JSON.stringify(args));
            }
        });
`
It work well!!!

The codes is as follows:

> \dotNetify-nuget_v.2.3.1-pre\ASP.NET Core Demo\WebApplication.Knockout\Views\HelloWorld.html

`
<!DOCTYPE html>
<html>
<head>
   <title></title>
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="/css/demo/bootstrap.min.css" rel="stylesheet">
   <script src="/lib/jquery.min.js"></script>
   <script src="/lib/require.min.js" data-main="/js/demo/demoApp"></script>
</head>
<body>
   <div class="container-fluid">
      <div class="header clearfix">
         <h3>Example: Hello World</h3>
      </div>
      <div class="jumbotron" data-vm="HelloWorldVM">
         <div class="row">
            <div class="col-md-6">
               <label>First name:</label>
               <input class="form-control" type="text" data-bind="value: FirstName" />
            </div>
            <div class="col-md-6">
               <label>Last name:</label>
               <input class="form-control" type="text" data-bind="value: LastName" />
            </div>
         </div>
         <hr />
         <div>
            Full name is <b><span data-bind="text: FullName" /></b>
         </div>
      </div>
   </div>
    <script>
        function getQueryString() {
            var args = {};
            var query = location.search.substring(1);
            var pairs = query.split("&");
            for (var i = 0; i < pairs.length; i++) {
                var pos = pairs[i].indexOf("=");
                if (pos == -1) {
                    continue;
                }
                var name = pairs[i].substring(0, pos);
                console.log(name);
                var value = pairs[i].substring(pos + 1);
                args[name] = value;
            }
            return args;
        }

        $(document).ready(function(){
            var qs = getQueryString();
            var args = { FirstName: qs.firstname, LastName: qs.lastname };
            if (args.FirstName || person.LastName) {
                $("[data-vm]").attr("data-vm-arg", JSON.stringify(args));
            }
        });
    </script>
</body>
</html>

`

> \dotNetify-nuget_v.2.3.1-pre\ASP.NET Core Demo\ViewModels\HelloWorldVM.cs
`
namespace ViewModels
{
   /// <summary>
   /// This view model demonstrates the two-way data binding between this server-side view model and the browser view.
   /// </summary>
   public class HelloWorldVM : BaseVM
   {
      public string FirstName
      {
         get { return Get<string>(); }
         set
         {
            Set(value);
            Changed(() => FullName);   // Raise the FullName's change event to update the view.
         }
      }

      public string LastName
      {
         get { return Get<string>(); }
         set
         {
            Set(value);
            Changed(() => FullName);   
         }
      }

      public string FullName
      {
         get { return FirstName + " " + LastName; }
      }

      /// <summary>
      /// Constructor.
      /// </summary>
      public HelloWorldVM()
      {
         FirstName = "Hello";
         LastName = "World";
      }
    }
}
`
The code work very well.
![helloworld2](https://user-images.githubusercontent.com/9990289/35405450-22faa51a-0241-11e8-9fe2-4682d7ba4c48.png)

I'm very thankful for your words and support. That fixed the problem I've been having.
