### ISSUE TITLE
Request to support RiotJS

### ISSUE THREAD

**Issue by ryzam** [dsuryd/dotNetify#74]
Hi 

I'm very interested in  your framework and would like request if possible to have riotjs support

**Comment by dsuryd** [comment]
Given the current roadmap focus on React, it's hardly possible for me to work with other front-end library as a primary contributor.  But I am open for collaboration in advisory/support capacity.

**Comment by dsuryd** [comment]
Closing this as out of scope, but anyone interested to own it, feel free to reopen.
