### ISSUE TITLE
How to build *.jsx

### ISSUE THREAD

**Issue by forconz** [dsuryd/dotNetify#76]
Such as \dotNetify-master\dotNetify-master\WebApplication.React\wwwroot\js\ControlTypes.jsx

I delete tow files( ControlTypes.js and ControlTypes.min.js).
**How to build ControlTypes.jsx and I can get ControlTypes.js and ControlTypes.min.js**

**1 I used react-tools, it worked not well.**
npm –g react-tools
 jsx --watch js/ js/

**2 And I used Babel, babel ControlTypes.jsx throw a error.**
Babel can compile ES2015 (the newest version of the JavaScript standard, also known as ES6) to ES5 (the version available in most JavaScript environments today).
npm install -g babel-cli
npm install --save-dev babel-cli babel-core babel-preset-es2015 babel-preset-react

PS C:\Users\lenovo\Downloads\dotNetify-master\dotNetify-master\WebApplication.React\wwwroot\js> babel ControlTypes.jsx
SyntaxError: ControlTypes.jsx: Unexpected token (23:9)
  21 |    render() {
  22 |       const radioButtons = this.state.RadioButtons.map(radio =>
> 23 |          <RadioButton key={radio.value} {...radio} />
     |          ^
  24 |       );
  25 |
  26 |       const selectFieldMenu = this.state.SelectFieldMenu.map(menu =>

I have not any idea to build / compile *.jsx

BTW:
webpact.config.js / module /loaders
Section (module) does not have config (loaders)
loader: 'babel', // 'babel-loader' is also a legal name to reference  

How to use file:compilerconfig.json ?

**The command (webpack -p) only create js file(wwwroot/lib/bundle.min.js), not build jsx.**
webpack -p
Hash: 1192952f150de17ba4be
Version: webpack 2.7.0
Time: 10367ms
                    Asset    Size  Chunks                    Chunk Names
wwwroot/lib/bundle.min.js  749 kB       0  [emitted]  [big]  main
   [0] ./~/react/index.js 190 bytes {0} [built]
   [1] ./~/prop-types/index.js 956 bytes {0} [built]
  [13] ./~/react-dom/index.js 1.36 kB {0} [built]
 [132] ./~/material-ui/Toggle/index.js 327 bytes {0} [built]
 [133] ./~/material-ui/styles/MuiThemeProvider.js 2.14 kB {0} [built]
 [134] ./~/material-ui/svg-icons/AV/movie.js 849 bytes {0} [built]
 [135] ./~/material-ui/svg-icons/action/delete.js 856 bytes {0} [built]
 [136] ./~/material-ui/svg-icons/action/search.js 1.01 kB {0} [built]
 [137] ./~/material-ui/svg-icons/communication/phone.js 1.07 kB {0} [built]
 [138] ./~/material-ui/svg-icons/content/create.js 936 bytes {0} [built]
 [139] ./~/material-ui/svg-icons/content/filter-list.js 865 bytes {0} [built]
 [140] ./~/promise-polyfill/promise.js 6.34 kB {0} [built]
 [141] ./~/whatwg-fetch/fetch.js 12.7 kB {0} [built]
 [142] ./wwwroot/lib/dotnetify-hub.js 15.4 kB {0} [built]
 [347] ./wwwroot/lib/app.js 2.73 kB {0} [built]
    + 333 hidden modules

**Comment by forconz** [comment]
npm install -g babel-cli
npm install babel-plugin-transform-react-jsx
babel --plugins transform-react-jsx js/HelloWorld.jsx --out-file js/HelloWorld.js

But the new HelloWorld.js is not same as the old HelloWorld.js
The code of new HelloWorld.js:
```
class HelloWorld extends React.Component {

   constructor(props) {
      super(props);

      // Connect this component to the back-end view model.
      this.vm = dotnetify.react.connect("HelloWorldVM", this);

      // Set up function to dispatch state to the back-end.
      this.dispatchState = state => {
         this.setState(state);
         this.vm.$dispatch(state);
      };

      // This component's JSX was loaded along with the VM's initial state for faster rendering.
      this.state = window.vmStates.HelloWorldVM;
   }
   componentWillUnmount() {
      this.vm.$destroy();
   }
   render() {
      return React.createElement(
         "div",
         { className: "container-fluid" },
         React.createElement(
            "div",
            { className: "header clearfix" },
            React.createElement(
               "h3",
               null,
               "Example: Hello World"
            )
         ),
         React.createElement(
            "div",
            { className: "jumbotron" },
            React.createElement(
               "div",
               { className: "row" },
               React.createElement(
                  "div",
                  { className: "col-md-6" },
                  React.createElement(TextBox, { data: { Label: "First name:", Placeholder: "Type first name here" },
                     value: this.state.FirstName,
                     onChange: value => this.setState({ FirstName: value }),
                     onUpdate: value => this.dispatchState({ FirstName: value }) })
               ),
               React.createElement(
                  "div",
                  { className: "col-md-6" },
                  React.createElement(TextBox, { data: { Label: "Last name:", Placeholder: "Type last name here" },
                     value: this.state.LastName,
                     onChange: value => this.setState({ LastName: value }),
                     onUpdate: value => this.dispatchState({ LastName: value }) })
               )
            ),
            React.createElement("hr", null),
            React.createElement(
               "div",
               null,
               "Full name is ",
               React.createElement(
                  "b",
                  null,
                  React.createElement(
                     "span",
                     null,
                     this.state.FullName
                  )
               )
            )
         )
      );
   }
}

class TextBox extends React.Component {
   constructor(props) {
      super(props);
      this.state = { changed: false };
      this.handleChange = this.handleChange.bind(this);
      this.handleBlur = this.handleBlur.bind(this);
   }
   handleChange(event) {
      this.setState({ changed: true });
      this.props.onChange(event.target.value);
   }
   handleBlur() {
      if (this.state.changed) this.props.onUpdate(this.props.value);
      this.setState({ changed: false });
   }
   render() {
      return React.createElement(
         "div",
         null,
         React.createElement(
            "label",
            null,
            this.props.data.Label
         ),
         React.createElement("input", { className: "form-control", type: "text",
            value: this.props.value,
            placeholder: this.props.data.Placeholder,
            onChange: this.handleChange,
            onBlur: this.handleBlur })
      );
   }
}

```

**Comment by forconz** [comment]
I move js folder to jsx folder, and created new empty folder:js
and I open Windows PowerShell, and exec command such as:
jsx --watch jsx/ js/

PS C:\Users\lenovo\Downloads\dotNetify-master\dotNetify-master\WebApplication.React\wwwroot> jsx --watch jsx/ js/
built Module("BookStore")
built Module("--ControlTypes")
built Module("BookStore.min")
built Module("--ControlTypes.min")
built Module("CompositeView")
built Module("CompositeView.min")
built Module("GridView")
built Module("HelloWorld.min")
built Module("HelloWorld")
built Module("Index")
built Module("LiveChart.min")
built Module("PaginatedTable.min")
built Module("LiveChart")
built Module("SecurePage")
built Module("SecurePage.min")
built Module("PaginatedTable")
built Module("GridView.min")
built Module("SignIn")
built Module("SimpleList")
built Module("SimpleList.min")
built Module("Index.min")
["--ControlTypes","--ControlTypes.min","BookStore","BookStore.min","CompositeView","CompositeView.min","GridView","GridV
iew.min","HelloWorld","HelloWorld.min","Index","Index.min","LiveChart","LiveChart.min","PaginatedTable","PaginatedTable.
min","SecurePage","SecurePage.min","SignIn","SimpleList","SimpleList.min"]

It work well.

The file \jsx\HelloWorld.js is same as \js\HelloWorld.js

**Comment by dsuryd** [comment]
It seems you're struggling with the tooling, not dotNetify specifically.   I suggest you start from the multitude of resources that are already available on how to set up a dotNetify-react project, from [detailed steps in the website](http://dotnetify.net/react/) to github demo projects [dotnetify-react-demo](https://github.com/dsuryd/dotnetify-react-demo), [dotnetify-react-demo-vs2017](https://github.com/dsuryd/dotnetify-react-demo-vs2017), and [dotnet template SPA](https://github.com/dsuryd/dotnetify-react-demo-vs2017/tree/master/ReactTemplate), so we can limit this forum only to reporting bugs or enhancements.  Thanks!

**Comment by forconz** [comment]
Thanks you very much.
