### ISSUE TITLE
Microsoft's new framework Blazor support

### ISSUE THREAD

**Issue by JohnLouderback** [dsuryd/dotNetify#78]
Microsoft just recently released an early version of Blazor - their C#/Razor in the browser framework. Looks very promising, and frankly, cool. I thought supporting this could be important as it would make our .NET web apps isomorphic if it were implemented into dotNetify.

### More information:
**Blog post 1**: https://blogs.msdn.microsoft.com/webdev/2018/02/06/blazor-experimental-project/
**Blog post 2**: https://blogs.msdn.microsoft.com/webdev/2018/03/22/get-started-building-net-web-apps-in-the-browser-with-blazor/
**Github**: https://github.com/aspnet/blazor
**Demo**: https://blazor-demo.github.io/
**Homepage**: https://learn-blazor.com/

**Comment by dsuryd** [comment]
Thank's for the info! It definitely looks great, and will start investigating it in earnest when it has SignalR client support (https://github.com/aspnet/Blazor/issues/20).

**Comment by desarrollo03TR** [comment]
What about Ooui? https://github.com/praeclarum/Ooui

There is an example using SignalR: https://github.com/solatticus/Ooui.Samples

It is a cool project.

**Comment by jaredthirsk** [comment]
@dsuryd Steve Sanderson of Microsoft has now closed that  aspnet/Blazor#20 with the recommendation of using this third party SignalR project, which implements the public part of the typescript SignalR library, minus the streaming.

https://github.com/BlazorExtensions/SignalR

**Comment by dsuryd** [comment]
I have started to look at this when v0.5 came out.  The idea I want to run with is, instead of rewriting the core script from scratch in C#, we may be able to use the javascript interop to run `dotnetify.connect` and pass a .NET callback method to update the Blazor component's state.

**Comment by mikaelliljedahl** [comment]
Would this only work for client side Blazor or would this also be useful for "Server-side" Blazor (a.k.a) Razor Components (I cannot see how the "client" would connect in the server-side case).

**Comment by dsuryd** [comment]
If anybody's still interested, here's a _dotNetified_ Blazor (v0.7) demo:

https://github.com/dsuryd/dotNetify/tree/master/Demo/Blazor

Check it out, and give me feedback. Thanks!

**Comment by dsuryd** [comment]
DotNetify-Blazor v1.0 is released.
