### ISSUE TITLE
Binding action (eg: button click)

### ISSUE THREAD

**Issue by WinInsider** [dsuryd/dotNetify#8]
It would be desirable to be able to bind button actions (click) to ICommand (System.Windows.Input)... is a well establish pattern in .NET circles.

In any case... really well written framework, brings View Models written in C# right into HTML

**Comment by dsuryd** [comment]
This wasn't implemented before because as I remembered it, the ICommand was defined in the WPF-specific PresentationCore.dll; but I only found out now that the interface was duplicated in System.dll since .NET 4.5.  So, thank's, this will be looked into for the next release.

**Comment by dsuryd** [comment]
Support for ICommand has been added in the master.  Examples provided in https://github.com/dsuryd/dotNetify-app-template.

**Comment by DG4ever** [comment]
I cant't get the vmCommand work inside a subclass as you did in the app-template with the MenuItemDTO.
The other Properties like Text are working as expeted, but the vmCommand won't get through when using a bool Property or an ICommand. However, when binding to a Property or ICommand directly inside the Viewmodel it is working.

In my case I got a List<SButtons>. The SButtons contains a Text Property and an ICommand. I am binding to each Element of the List separatly.

My html code looks like this:

`<button data-bind="text: SButtons()[0].Text, vmCommand:  SButtons()[0].ClickCommand" type="button" class="btn btn-default"></button>`
