### ISSUE TITLE
Stop working in react native background state

### ISSUE THREAD

**Issue by Shhzdmrz** [dsuryd/dotNetify#82]
Hi,

Thank you for the package but wondering is it the standard way the package must be used when the app is in active state? and will not work in app background state.

**Comment by dsuryd** [comment]
Mobile OSes normally restrict any app's activity when in background state, which hampers the ability for SignalR to stay connected.  If you need some kind of push notification capability when app is running in the background, SignalR (and by extension dotNetify) is not appropriate for such task.
