### ISSUE TITLE
open source site http://dotnetify.net/react

### ISSUE THREAD

**Issue by jmptrader** [dsuryd/dotNetify#85]
Dear,

In the site http://dotnetify.net/react has many interest parts (b.e. show traffic)

do you can open source this project?

Thank's,
JM

**Comment by dsuryd** [comment]
The source code of every example in there was already available on this github.  And the traffic part is just this:
```jsx
dotnetify.debugFn = (vmId, direction, vmData) => {
   var traffics = this.state.traffics;
   traffics.push({ vmId: vmId, direction: direction, vmData: vmData });
   this.setState({ traffics: traffics });
}
```

**Comment by jmptrader** [comment]
Thank's an lot.
