### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify#87]
What would be involved in connecting dotNetify to an Angular project rather than React?

**Comment by dsuryd** [comment]
Not much, as it turned out:

```ts
import { Component, OnInit } from '@angular/core';
const dotnetify: any = require('dotnetify');

@Component({
    selector: 'hello-world',
    template: `
      <div>{{state.Greetings}}</div>
      <div>{{state.ServerTime}}</div>
    `
})
export class HelloWorldComponent implements OnInit {

   state: any = {};
   vm: any;

   ngOnInit() {
      this.vm = dotnetify.connect("HelloWorld", {
        getState: () => this.getState(), 
        setState: (state: any) => this.setState(state)
      });
   }

   ngOnDestroy() {
      this.vm.$destroy();
   }

   getState() {
      return this.state;
   }

   setState(state: any) {
      this.state = Object.assign({}, this.state, state);
   }
}
```

**Comment by jwyackel** [comment]
Thank you for your help I will try that out.
Great work on the DotNetify project.

**Comment by dj-fiorex** [comment]
Is still possible to integrate dotnetify with angular? because i've tried to add dotnetify to my angular app but it requires react.
Please help, i'm working in a big project and i want to integrate your marvelous library

**Comment by dsuryd** [comment]
You will need to downgrade to dotnetify npm v3.0.2 until there's future update.

**Comment by dj-fiorex** [comment]
> You will need to downgrade to dotnetify npm v3.0.2 until there's future update.

Thanks for the answer, in your opinion is possible to write a port or to adapt dotnetify with NativeScript? 
There is no window there... ;)

**Comment by dsuryd** [comment]
I cannot say as I'm not familiar with how NativeScript works, but if it can run SignalR client, then it's possible.
