### ISSUE TITLE
TypeScript support and templates

### ISSUE THREAD

**Issue by MrFoxPro** [dsuryd/dotNetify#90]

**Comment by dsuryd** [comment]
I don't currently use Typescript for this; but there's a typed definition in the dist folder made by a contributor.  You're welcome to PR if you want to help with extending the support.

**Comment by MrFoxPro** [comment]
@dsuryd typings arent available via npm!

**Comment by dsuryd** [comment]
The merges aren't published yet.

**Comment by dsuryd** [comment]
Typings published.
