### ISSUE TITLE
Divide server and client 

### ISSUE THREAD

**Issue by MrFoxPro** [dsuryd/dotNetify#91]
Hi. Is it possible to divide client from server? I want to debug and develop separately. How to do it right? Thank you in advance

**Comment by dsuryd** [comment]
You mean separating the webpack build process from ASP.NET Core ?  Sure, all you have to is create separate projects for the React code and the C# code.  You can use create-react-app CLI for the client-side.

**Comment by MrFoxPro** [comment]
Got it
