### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MrFoxPro** [dsuryd/dotNetify#95]
Im trying to connect ofiicial dontet react template and Dotnetify library, but getting error: 'Method not found: 'Void Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub(System.String)'.'
![image](https://user-images.githubusercontent.com/17229619/40511327-c0599774-5fb8-11e8-96d2-475cdad72722.png)

repo: https://github.com/MrFoxPro/dotnet_react_dotnetify

**Comment by dsuryd** [comment]
I suspect signalR nuget version mismatch.  Published dotNetify nuget is on preview2, not rc1-final.

**Comment by MrFoxPro** [comment]
@dsuryd 
I changed it to `<ItemGroup>
    <PackageReference Include="DotNetify.SignalR" Version="3.0.0-pre" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
    <PackageReference Include="System.Reactive" Version="3.1.1" />
    <PackageReference Include="AspNet.Security.OpenIdConnect.Server" Version="2.0.0-rc1-final" />    
  </ItemGroup>`,
,restored packages but nothing was changed

**Comment by dsuryd** [comment]
Your solution is using ASP.NET Core v2.1.0-rc1  You cannot use DotNetify v3.0.0-pre from nuget, it's still dependent on v2.0.  If you want to make this work, use the latest dotNetify source code from this github, they will work v2.10-rc1.

**Comment by dsuryd** [comment]
Should now work with v3.0 release.
