### ISSUE TITLE
Any expected performance issues pushing large collections from the server?

### ISSUE THREAD

**Issue by mrayva** [dsuryd/dotNetify#98]
Any benchmarks, guidance? 
Let's say a model has a property-List with 1000 items ( to be displayed in front-end data grid ) and only 10% get externally updated every second. Will the entire list get pushed to the client?

**Comment by dsuryd** [comment]
We certainly don’t want to push the entire list for updates. There are CRUD APIs for this, documented in the website.

**Comment by dsuryd** [comment]
I hope I've answered the question, so I'm closing this.
