### ISSUE TITLE
Are there events to hook into when request to server is sent and data is received?

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify#99]
When I turn on the dotnetify debug, I can see console statements printed when the request to the ViewModel is sent and when the data is received.

Is there a way to hook into these so for data retrieval that takes a few seconds to show a loading indicator on the screen?

I could probably set a variable in the viewmodel state and have it update when the server sends the data back.  I do have an idea on which requests will take a fair amount of time, so if I had to do it this way it wouldn't be too bad.

**Comment by dsuryd** [comment]
You can hook into that with debugFn (see #85), but then you'd have to enable debug all the time!  The other idea with the view model state is better and a common approach in MVVM.

**Comment by jwyackel** [comment]
Thanks for the response, I will try the view model idea first.
